---
# Transform tls-boots -> boots-ca-cert in orch-gateway
apiVersion: batch/v1
kind: Job
metadata:
  name: transform-boots-ca-gateway
  namespace: orch-gateway
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: reflector-setup
      restartPolicy: OnFailure
      containers:
      - name: transform
        image: bitnami/kubectl:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -e
          echo "Waiting for reflected secret tls-boots..."
          timeout=300
          elapsed=0
          while [ $elapsed -lt $timeout ]; do
            if kubectl get secret tls-boots -n orch-gateway 2>/dev/null; then
              echo "Source secret found, creating transformed secret..."
              CA_CERT=$(kubectl get secret tls-boots -n orch-gateway -o jsonpath='{.data.tls\.crt}')
              kubectl create secret generic boots-ca-cert -n orch-gateway \
                --from-literal=ca.crt=$(echo "$CA_CERT" | base64 -d) \
                --dry-run=client -o yaml | kubectl apply -f -
              echo "Transformed secret boots-ca-cert created!"
              exit 0
            fi
            sleep 5
            elapsed=$((elapsed + 5))
          done
          echo "Timeout waiting for tls-boots"
          exit 1
---
# Transform tls-orch -> gateway-ca-cert in orch-infra  
apiVersion: batch/v1
kind: Job
metadata:
  name: transform-gateway-ca-infra
  namespace: orch-infra
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: reflector-setup
      restartPolicy: OnFailure
      containers:
      - name: transform
        image: bitnami/kubectl:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -e
          echo "Waiting for reflected secret tls-orch..."
          timeout=300
          elapsed=0
          while [ $elapsed -lt $timeout ]; do
            if kubectl get secret tls-orch -n orch-infra 2>/dev/null; then
              echo "Source secret found, creating transformed secret..."
              {{- if .Values.generateOrchCert }}
              CA_CERT=$(kubectl get secret tls-orch -n orch-infra -o jsonpath='{.data.ca\.crt}')
              {{- else }}
              CA_CERT=$(kubectl get secret tls-orch -n orch-infra -o jsonpath='{.data.tls\.crt}')
              {{- end }}
              kubectl create secret generic gateway-ca-cert -n orch-infra \
                --from-literal=ca.crt=$(echo "$CA_CERT" | base64 -d) \
                --dry-run=client -o yaml | kubectl apply -f -
              echo "Transformed secret gateway-ca-cert created!"
              exit 0
            fi
            sleep 5
            elapsed=$((elapsed + 5))
          done
          echo "Timeout waiting for tls-orch"
          exit 1
---
# Transform tls-orch -> tls-ca in cattle-system
apiVersion: batch/v1
kind: Job
metadata:
  name: transform-gateway-ca-cattle
  namespace: cattle-system
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: reflector-setup
      restartPolicy: OnFailure
      containers:
      - name: transform
        image: bitnami/kubectl:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -e
          echo "Waiting for reflected secret tls-orch..."
          timeout=300
          elapsed=0
          while [ $elapsed -lt $timeout ]; do
            if kubectl get secret tls-orch -n cattle-system 2>/dev/null; then
              echo "Source secret found, creating transformed secret..."
              {{- if .Values.generateOrchCert }}
              CA_CERT=$(kubectl get secret tls-orch -n cattle-system -o jsonpath='{.data.ca\.crt}')
              {{- else }}
              CA_CERT=$(kubectl get secret tls-orch -n cattle-system -o jsonpath='{.data.tls\.crt}')
              {{- end }}
              kubectl create secret generic tls-ca -n cattle-system \
                --from-literal=cacerts.pem=$(echo "$CA_CERT" | base64 -d) \
                --dry-run=client -o yaml | kubectl apply -f -
              echo "Transformed secret tls-ca created!"
              exit 0
            fi
            sleep 5
            elapsed=$((elapsed + 5))
          done
          echo "Timeout waiting for tls-orch"
          exit 1
---
# Transform tls-boots -> boots-ca-cert in orch-infra
apiVersion: batch/v1
kind: Job
metadata:
  name: transform-boots-ca-infra
  namespace: orch-infra
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: reflector-setup
      restartPolicy: OnFailure
      containers:
      - name: transform
        image: bitnami/kubectl:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -e
          echo "Waiting for reflected secret tls-boots..."
          timeout=300
          elapsed=0
          while [ $elapsed -lt $timeout ]; do
            if kubectl get secret tls-boots -n orch-infra 2>/dev/null; then
              echo "Source secret found, creating transformed secret..."
              CA_CERT=$(kubectl get secret tls-boots -n orch-infra -o jsonpath='{.data.tls\.crt}')
              kubectl create secret generic boots-ca-cert -n orch-infra \
                --from-literal=ca.crt=$(echo "$CA_CERT" | base64 -d) \
                --dry-run=client -o yaml | kubectl apply -f -
              echo "Transformed secret boots-ca-cert created!"
              exit 0
            fi
            sleep 5
            elapsed=$((elapsed + 5))
          done
          echo "Timeout waiting for tls-boots"
          exit 1
---
# Transform tls-gitea -> gitea-ca-cert in orch-app
apiVersion: batch/v1
kind: Job
metadata:
  name: transform-gitea-ca-app
  namespace: orch-app
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: reflector-setup
      restartPolicy: OnFailure
      containers:
      - name: transform
        image: bitnami/kubectl:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -e
          echo "Waiting for reflected secret tls-gitea..."
          timeout=300
          elapsed=0
          while [ $elapsed -lt $timeout ]; do
            if kubectl get secret tls-gitea -n orch-app 2>/dev/null; then
              echo "Source secret found, creating transformed secret..."
              CA_CERT=$(kubectl get secret tls-gitea -n orch-app -o jsonpath='{.data.tls\.crt}')
              kubectl create secret generic gitea-ca-cert -n orch-app \
                --from-literal=ca.crt=$(echo "$CA_CERT" | base64 -d) \
                --dry-run=client -o yaml | kubectl apply -f -
              echo "Transformed secret gitea-ca-cert created!"
              exit 0
            fi
            sleep 5
            elapsed=$((elapsed + 5))
          done
          echo "Timeout waiting for tls-gitea"
          exit 1
---
# Transform tls-gitea -> gitea-ca-cert in orch-cluster
apiVersion: batch/v1
kind: Job
metadata:
  name: transform-gitea-ca-cluster
  namespace: orch-cluster
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: reflector-setup
      restartPolicy: OnFailure
      containers:
      - name: transform
        image: bitnami/kubectl:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -e
          echo "Waiting for reflected secret tls-gitea..."
          timeout=300
          elapsed=0
          while [ $elapsed -lt $timeout ]; do
            if kubectl get secret tls-gitea -n orch-cluster 2>/dev/null; then
              echo "Source secret found, creating transformed secret..."
              CA_CERT=$(kubectl get secret tls-gitea -n orch-cluster -o jsonpath='{.data.tls\.crt}')
              kubectl create secret generic gitea-ca-cert -n orch-cluster \
                --from-literal=ca.crt=$(echo "$CA_CERT" | base64 -d) \
                --dry-run=client -o yaml | kubectl apply -f -
              echo "Transformed secret gitea-ca-cert created!"
              exit 0
            fi
            sleep 5
            elapsed=$((elapsed + 5))
          done
          echo "Timeout waiting for tls-gitea"
          exit 1
