# SPDX-FileCopyrightText: 2026 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

version: 2
enable-beta-ecosystems: true

updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    commit-message:
      prefix: "Go modules"
    reviewers:
      - "dmytroye"
    cooldown:
      default-days: 7

  # Terraform
  - package-ecosystem: "terraform"
    directory: "/terraform/edge-network"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    schedule:
      interval: monthly
    commit-message:
      prefix: "terraform"
    reviewers:
      - "dmytroye"
    cooldown:
      default-days: 7

  - package-ecosystem: "terraform"
    directory: "/terraform/orchestrator"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    schedule:
      interval: monthly
    commit-message:
      prefix: "terraform"
    reviewers:
      - "dmytroye"
    cooldown:
      default-days: 7

  - package-ecosystem: "terraform"
    directory: "/terraform/edge-storage-pool"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    schedule:
      interval: monthly
    commit-message:
      prefix: "terraform"
    reviewers:
      - "dmytroye"
    cooldown:
      default-days: 7

  - package-ecosystem: "terraform"
    directory: "/pod-configs/orchestrator/cluster"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    schedule:
      interval: monthly
    commit-message:
      prefix: "terraform"
    reviewers:
      - "dmytroye"
    cooldown:
      default-days: 7

  - package-ecosystem: "terraform"
    directory: "/pod-configs/orchestrator/orch-load-balancer"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    schedule:
      interval: monthly
    commit-message:
      prefix: "terraform"
    reviewers:
      - "dmytroye"
    cooldown:
      default-days: 7

  - package-ecosystem: "terraform"
    directory: "/pod-configs/orchestrator/orch-route53"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    schedule:
      interval: monthly
    commit-message:
      prefix: "terraform"
    reviewers:
      - "dmytroye"
    cooldown:
      default-days: 7

  - package-ecosystem: "terraform"
    directory: "/pod-configs/orchestrator/pull-through-cache-proxy"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    schedule:
      interval: monthly
    commit-message:
      prefix: "terraform"
    reviewers:
      - "dmytroye"
    cooldown:
      default-days: 7

  - package-ecosystem: "terraform"
    directory: "/pod-configs/module/lb-target-group-attachment"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    schedule:
      interval: monthly
    commit-message:
      prefix: "terraform"
    reviewers:
      - "dmytroye"
    cooldown:
      default-days: 7

  - package-ecosystem: "terraform"
    directory: "/pod-configs/module/application-load-balancer"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    schedule:
      interval: monthly
    commit-message:
      prefix: "terraform"
    reviewers:
      - "dmytroye"
    cooldown:
      default-days: 7

  - package-ecosystem: "terraform"
    directory: "/pod-configs/module/load-balancer"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    schedule:
      interval: monthly
    commit-message:
      prefix: "terraform"
    reviewers:
      - "dmytroye"
    cooldown:
      default-days: 7

  - package-ecosystem: "terraform"
    directory: "/pod-configs/buckets"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    schedule:
      interval: monthly
    commit-message:
      prefix: "terraform"
    reviewers:
      - "dmytroye"
    cooldown:
      default-days: 7

  # Helm
  - package-ecosystem: "helm"
    directory: "/argocd-internal/applications"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    commit-message:
      prefix: "Helm"
    reviewers:
      - "dmytroye"
    cooldown:
      default-days: 7

  - package-ecosystem: "helm"
    directory: "/argocd-internal/root-app"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    commit-message:
      prefix: "Helm"
    reviewers:
      - "dmytroye"
    cooldown:
      default-days: 7

  - package-ecosystem: "helm"
    directory: "/argocd/applications"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    commit-message:
      prefix: "Helm"
    reviewers:
      - "dmytroye"
    cooldown:
      default-days: 7

  - package-ecosystem: "helm"
    directory: "/argocd/root-app"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    commit-message:
      prefix: "Helm"
    reviewers:
      - "dmytroye"
    cooldown:
      default-days: 7

  # Docker
  - package-ecosystem: "docker"
    directory: "/installer"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    commit-message:
      prefix: "Dockerfile"
    reviewers:
      - "dmytroye"
    cooldown:
      default-days: 7

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 15
    commit-message:
      prefix: "Github Actions"
    reviewers:
      - "dmytroye"
    cooldown:
      default-days: 7
