# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

version: "2"

run:
  timeout: 5m
  tests: true
linters:
  enable-all: true
  # TODO: Fix linting issues and enable all linters.
  disable:
    - canonicalheader
    - cyclop
    - depguard
    - dupl
    - durationcheck
    - err113
    - exhaustruct
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - godot
    - godox
    - gomoddirectives
    - goprintffuncname
    - gosec
    - intrange
    - ireturn
    - lll
    - mnd
    - musttag
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - revive
    - tagalign
    - tagliatelle
    - unparam
    - usestdlibvars
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
issues:
  exclude:
    - SA1019.*
