# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

run:
  timeout: 5m
  tests: true
linters:
  enable-all: true
  # TODO: Fix linting issues and enable all linters.
  disable:
    - cyclop
    - depguard
    - dupl
    - durationcheck
    - exhaustruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - godot
    - godox
    - goerr113
    - gomoddirectives
    - gomnd
    - goprintffuncname
    - gosec
    - ireturn
    - lll
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nonamedreturns
    - paralleltest
    - prealloc
    - revive
    - stylecheck
    - tagliatelle
    - unparam
    - usestdlibvars
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
issues:
  exclude:
    - SA1019.*
