namespaces:
  - name: "orch-infra"
    labels:
      istio-injection: enabled
  - name: "orch-iam"
    labels:
      istio-injection: enabled
  - name: "orch-platform"
    labels:
      istio-injection: enabled
  - name: "fleet-default"
    labels:
      app.edge-orchestrator.intel.com/fleet-rs-secret: "true"
