\SPDX-FileCopyrightText: 2025 Intel Corporation
\
\SPDX-License-Identifier: Apache-2.0

.TH onprem-KE INSTALLER "17" "November 2023" "onprem-ke-installer 0.1.0" "User Commands"
.SH NAME
onprem-ke-installer \- manual page for onprem-ke-installer 0.1.0
.SH DESCRIPTION
.IP
USAGE: onprem-ke-installer
.SH "SEE ALSO"
.IP
Website: https://github.com/open-edge-platform/edge-manageability-framework/on-prem-installers
.SH "OTHER"
.IP
Made by Intel with ❤️
.IP
This program is distributed under Apache 2.0 license.
