# Default values for keycloak-config
# This is used by the official Keycloak operator

keycloak:
  name: platform-keycloak
  instances: 1
  
  # Bootstrap admin from secret
  bootstrapAdmin:
    user:
      secret: platform-keycloak
  
  # Basic configuration
  hostname:
    strict: false
  
  http:
    httpEnabled: true
    httpPort: 8080
  
  proxy:
    headers: xforwarded
  
  # Resource limits
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  
  # Ingress disabled by default
  ingress:
    enabled: false