{{- if .Values.keycloak.enabled }}
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: {{ .Values.keycloak.instanceName }}
  namespace: {{ .Values.keycloak.instanceNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "150"
spec:
  instances: {{ .Values.keycloak.instances | default 1 }}
  
  {{- if .Values.keycloak.hostname }}
  hostname:
    strict: {{ .Values.keycloak.hostname.strict | default false }}
  {{- end }}
  
  {{- if .Values.keycloak.http }}
  http:
    httpEnabled: {{ .Values.keycloak.http.httpEnabled | default true }}
    httpPort: {{ .Values.keycloak.http.httpPort | default 8080 }}
  {{- end }}
  
  {{- if .Values.keycloak.proxy }}
  proxy:
    headers: {{ .Values.keycloak.proxy.headers | default "xforwarded" }}
  {{- end }}
  
  {{- if .Values.keycloak.db }}
  db:
    vendor: {{ .Values.keycloak.db.vendor | default "postgres" }}
    host: {{ .Values.keycloak.db.host }}
    port: {{ .Values.keycloak.db.port | default 5432 }}
    database: {{ .Values.keycloak.db.database }}
    usernameSecret:
      name: {{ .Values.keycloak.db.usernameSecret.name }}
      key: {{ .Values.keycloak.db.usernameSecret.key }}
    passwordSecret:
      name: {{ .Values.keycloak.db.passwordSecret.name }}
      key: {{ .Values.keycloak.db.passwordSecret.key }}
  {{- end }}
  
  {{- if .Values.keycloak.additionalOptions }}
  additionalOptions:
    {{- range .Values.keycloak.additionalOptions }}
    - name: {{ .name }}
      value: {{ .value | quote }}
    {{- end }}
  {{- end }}
  
  {{- if .Values.keycloak.resources }}
  resources:
    {{- if .Values.keycloak.resources.requests }}
    requests:
      {{- if .Values.keycloak.resources.requests.cpu }}
      cpu: {{ .Values.keycloak.resources.requests.cpu }}
      {{- end }}
      {{- if .Values.keycloak.resources.requests.memory }}
      memory: {{ .Values.keycloak.resources.requests.memory }}
      {{- end }}
    {{- end }}
    {{- if .Values.keycloak.resources.limits }}
    limits:
      {{- if .Values.keycloak.resources.limits.cpu }}
      cpu: {{ .Values.keycloak.resources.limits.cpu }}
      {{- end }}
      {{- if .Values.keycloak.resources.limits.memory }}
      memory: {{ .Values.keycloak.resources.limits.memory }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}