# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

{{- $appName        := "aws-lb" }}
{{- $namespace      := "kube-system" }}
{{- $syncWave       := "110" }}
---
{{- if (index .Values.argo.enabled $appName) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "{{ $syncWave }}"
  name: {{$appName}}
  namespace: {{ required "A valid namespace entry required!" .Values.argo.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ required "A valid projectName entry required!" .Values.argo.project }}
  sources:
    - repoURL: https://aws.github.io/eks-charts
      chart: aws-load-balancer-controller
      targetRevision: 1.12.0
      helm:
        releaseName: {{$appName}}
        valuesObject:
          {{- $customFile := printf "custom/%s.tpl" $appName }}
          {{- $customConfig := tpl (.Files.Get $customFile) . | fromYaml }}
          {{- $baseFile := printf "configs/%s.yaml" $appName }}
          {{- $baseConfig := .Files.Get $baseFile|fromYaml}}
          {{- $overwrite := (get .Values.postCustomTemplateOverwrite $appName ) | default dict }}
          {{- mergeOverwrite $baseConfig $customConfig $overwrite | toYaml | nindent 10 }}
  destination:
    namespace: {{$namespace}}
    server: {{ required "A valid targetServer entry required!" .Values.argo.targetServer }}
  syncPolicy:
    {{- if .Values.argo.autosync }}
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    {{- end }}
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  # https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2312
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: aws-load-balancer-tls
    jsonPointers:
    - /data
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: aws-load-balancer-webhook
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: aws-load-balancer-webhook
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'
{{- end }}
