# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

{{- $appName        := "keycloak-operator-install" }}
{{- $namespace      := "keycloak-system" }}
{{- $syncWave       := "100" }}
---
{{- if (index .Values.argo.enabled $appName) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "{{ $syncWave }}"
  name: {{$appName}}
  namespace: {{ required "A valid namespace entry required!" .Values.argo.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ required "A valid projectName entry required!" .Values.argo.project }}
  source:
    repoURL: {{ .Values.argo.deployRepoURL }}
    path: argocd/charts/keycloak-operator-install
    targetRevision: {{ .Values.argo.deployRepoRevision | quote}}
    helm:
      releaseName: {{$appName}}
      valuesObject:
        operator:
          namespace: {{$namespace}}
  destination:
    namespace: {{$namespace}}
    server: {{ required "A valid targetServer entry required!" .Values.argo.targetServer }}
  syncPolicy:
    {{- if .Values.argo.autosync }}
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    {{- end }}
    syncOptions:
      - CreateNamespace=true
      - Replace=true
{{- end }}