# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

{{- $appName        := "platform-keycloak" }}
{{- $namespace      := "keycloak-system" }}
{{- $syncWave       := "150" }}
---
{{- if (index .Values.argo.enabled $appName) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "{{ $syncWave }}"
    description: "Keycloak instance deployed via Operator"
  name: {{$appName}}
  namespace: {{ required "A valid namespace entry required!" .Values.argo.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ required "A valid projectName entry required!" .Values.argo.project }}
  sources:
    - repoURL: {{ required "A valid deployRepoURL entry required!" .Values.argo.deployRepoURL }}
      path: argocd/keycloak-operator/keycloak-instance
      targetRevision: {{ required "A valid deployRepoRevision entry required!" .Values.argo.deployRepoRevision }}
      helm:
        valuesObject:
          # Cluster-specific values for Keycloak Operator realm configuration
          clusterSpecific:
            webuiClientRootUrl: "https://web-ui.{{ .Values.argo.clusterDomain }}"
            webuiRedirectUrls:
              - "https://web-ui.{{ .Values.argo.clusterDomain }}"
              - "https://app-service-proxy.{{ .Values.argo.clusterDomain }}/app-service-proxy-index.html*"
              - "https://vnc.{{ .Values.argo.clusterDomain }}/*"
              - "https://{{ .Values.argo.clusterDomain }}"
              {{- if index .Values.argo "platform-keycloak" "extraUiRedirects" }}
              {{- $extraUiRedirects := index .Values.argo "platform-keycloak" "extraUiRedirects" }}
              {{- if typeIs "string" $extraUiRedirects }}
              {{- range $extraUiRedirects | split "," }}
              - {{ . | quote }}
              {{- end }}
              {{- else }}
              {{- range $extraUiRedirects }}
              - {{ . | quote }}
              {{- end }}
              {{- end }}
              {{- end }}
            docsuiClientRootUrl: "https://docs-ui.{{ .Values.argo.clusterDomain }}"
            docsuiRedirectUrls:
              - "https://docs-ui.{{ .Values.argo.clusterDomain }}"
              - "https://docs-ui.{{ .Values.argo.clusterDomain }}/"
            registryClientRootUrl: "https://registry-oci.{{ .Values.argo.clusterDomain }}"
            telemetryClientRootUrl: "https://observability-ui.{{ .Values.argo.clusterDomain }}"
            telemetryRedirectUrls:
              - "https://observability-admin.{{ .Values.argo.clusterDomain }}/login/generic_oauth"
              - "https://observability-ui.{{ .Values.argo.clusterDomain }}/login/generic_oauth"
            clusterManagementClientRootUrl: "https://cluster-management.{{ .Values.argo.clusterDomain }}"
            clusterManagementRedirectUrls:
              - "https://cluster-management.{{ .Values.argo.clusterDomain }}"
              - "https://cluster-management.{{ .Values.argo.clusterDomain }}/"
          keycloak:
            instances: 1
            proxy:
              headers: xforwarded
          # Database configuration is now directly managed via Keycloak CRD v2alpha1
          # in argocd/keycloak-operator/keycloak-instance/templates/keycloak.yaml
          # These values are kept for reference but not used by the operator
          # database:
          #   vendor: postgres
          #   host: postgresql-cluster-rw.orch-database.svc.cluster.local
          #   port: 5432
          #   database: keycloak-system-platform-keycloak
          #   usernameSecret: keycloak-platform-db
          #   passwordSecret: keycloak-platform-db
          http:
            port: 8080
            relativeUrls: true
          envProxy:
            httpsProxy: {{ .Values.argo.proxy.httpsProxy | quote }}
            httpProxy: {{ .Values.argo.proxy.httpProxy | quote }}
            noProxy: {{ .Values.argo.proxy.noProxy | quote }}
          {{- with .Values.argo.resources.platformKeycloak }}
          resources:
            {{- toYaml . | nindent 12}}
          {{- end }}
          realmConfig:
            displayName: "Keycloak"
            accountTheme: "keycloak"
            displayNameHtml: "<img src='https://raw.githubusercontent.com/open-edge-platform/orch-utils/73df5d1e99a81ae333d94b1c47dd9bef7fa03ae9/keycloak/one-edge-platform-login-title.png'></img>"
            defaultSignatureAlgorithm: "PS512"
            accessTokenLifespan: 3600
            ssoSessionIdleTimeout: 5400
            ssoSessionMaxLifespan: 43200
            passwordPolicy: "length(14) and digits(1) and specialChars(1) and upperCase(1) and lowerCase(1)"
            bruteForceProtected: true
            permanentLockout: false
            maxFailureWaitSeconds: 900
            minimumQuickLoginWaitSeconds: 60
            waitIncrementSeconds: 300
            quickLoginCheckMilliSeconds: 200
            maxDeltaTimeSeconds: 43200
            failureFactor: 5
  destination:
    namespace: {{$namespace}}
    server: {{ required "A valid targetServer entry required!" .Values.argo.targetServer }}
  syncPolicy:
    {{- if .Values.argo.autosync }}
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    {{- end }}
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
{{- end }}
