# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

{{- $appName        := "reflector-setup" }}
{{- $namespace      := "orch-secret" }}
{{- $syncWave       := "1400" }}
---
{{- if (index .Values.argo.enabled "reflector") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "{{ $syncWave }}"
  name: {{$appName}}
  namespace: {{ required "A valid namespace entry required!" .Values.argo.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ required "A valid projectName entry required!" .Values.argo.project }}
  source:
    repoURL: {{ required "A valid gitRepoURL entry required!" .Values.argo.gitRepoURL }}
    path: node/secret-reflector-setup
    targetRevision: {{ required "A valid targetRevision entry required!" .Values.argo.targetRevision }}
    helm:
      releaseName: {{$appName}}
      valuesObject:
        clusterDomain: {{ .Values.argo.clusterDomain }}
        generateOrchCert: {{ index .Values.argo "self-signed-cert" "generateOrchCert" | default false }}
        reflectorRules:
          - sourceNamespace: orch-boots
            sourceSecret: tls-boots
            targetNamespaces: 
              - orch-gateway
              - orch-infra
          - sourceNamespace: orch-gateway
            sourceSecret: tls-orch
            targetNamespaces:
              - orch-infra
              - cattle-system
          - sourceNamespace: orch-platform
            sourceSecret: platform-keycloak
            targetNamespaces:
              - orch-infra
          - sourceNamespace: orch-platform
            sourceSecret: gitea-app-credential
            targetNamespaces:
              - fleet-system
          - sourceNamespace: orch-platform
            sourceSecret: gitea-cluster-credential
            targetNamespaces:
              - fleet-system
          - sourceNamespace: gitea
            sourceSecret: tls-gitea
            targetNamespaces:
              - orch-app
              - orch-cluster
  destination:
    namespace: {{$namespace}}
    server: {{ required "A valid targetServer entry required!" .Values.argo.targetServer }}
  syncPolicy:
    {{- if .Values.argo.autosync }}
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    {{- end }}
    syncOptions:
      - CreateNamespace=true
{{- end }}
