# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

{{- $appName        := "reflector" }}
{{- $namespace      := "orch-secret" }}
{{- $syncWave       := "200" }}
---
{{- if (index .Values.argo.enabled $appName) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "{{ $syncWave }}"
  name: {{$appName}}
  namespace: {{ required "A valid namespace entry required!" .Values.argo.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ required "A valid projectName entry required!" .Values.argo.project }}
  source:
    repoURL: https://emberstack.github.io/helm-charts
    chart: reflector
    targetRevision: 7.1.288
    helm:
      releaseName: {{$appName}}
      valuesObject:
        {{- $customFile := printf "custom/%s.tpl" $appName }}
        {{- if $.Files.Get $customFile }}
        {{- $customConfig := tpl (.Files.Get $customFile) . | fromYaml }}
        {{- $baseFile := printf "configs/%s.yaml" $appName }}
        {{- $baseConfig := .Files.Get $baseFile|fromYaml}}
        {{- $overwrite := (get .Values.postCustomTemplateOverwrite $appName ) | default dict }}
        {{- mergeOverwrite $baseConfig $customConfig $overwrite | toYaml | nindent 10 }}
        {{- end }}
      - CreateNamespace=true
{{- end }}
