# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: dev-coder
id: dev
enableObservability: true
enableAuditLogging: true
enableKyverno: true
enableAutoProvision: false
enableUiDev: true
enableAutoCert: false
enableCoder: true
enableMailpit: true
targetCluster: kind
enableOsrmManualMode: true
