# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

# Enable PostgreSQL secrets deployment
enabled: true

# Target namespace for Helm release
namespace: orch-database

# Helm release name
releaseName: postgresql-secrets

# OCI or Helm chart URL
chartURL: "oci://registry-rs.edgeorchestration.intel.com/edge-orch/common/charts/postgresql-secrets"

# Chart version
version: "26.0.1"

# Database secrets configuration
databases:
  - namespace: orch-platform
    name: platform-keycloak
  - namespace: orch-platform
    name: vault
  - namespace: orch-infra
    name: inventory
  - namespace: orch-infra
    name: alerting
  - namespace: orch-iam
    name: iam-tenancy
  - namespace: orch-infra
    name: mps
  - namespace: orch-infra
    name: rps
# Host for the database cluster
host: "postgresql-cluster-rw.orch-database"

# Annotations for secrets
annotations:
  cnpg.io/reload: "false"

# Autosync-like behavior
autosync: true
