# SPDX-FileCopyrightText: 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: platform-keycloak
  namespace: keycloak-system
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: platform-keycloak
    app.kubernetes.io/version: "26.4.5"
spec:
  image: quay.io/keycloak/keycloak:26.4.5
  
  # NOW TRUE - init container will build it
  startOptimized: true
  
  bootstrapAdmin:
    user:
      secret: platform-keycloak
  
  db:
    vendor: postgres
    host: postgresql-cluster-rw.orch-database.svc.cluster.local
    port: 5432
    database: keycloak-system-platform-keycloak
    usernameSecret:
      name: keycloak-platform-db
      key: username
    passwordSecret:
      name: keycloak-platform-db
      key: password
    poolInitialSize: 5
    poolMinSize: 5
    poolMaxSize: 50
  
  http:
    httpEnabled: true
    httpPort: 8080
    annotations: {}
    labels: {}
  
  ingress:
    enabled: false
  
  proxy:
    headers: xforwarded
  
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 2Gi
  
  # All your runtime options (these become environment variables)
  additionalOptions:
    # Keycloak Hostname v2 Configuration (Keycloak 25+)
    # CRITICAL ISSUE:
    # Keycloak's hostname setting determines the issuer URL in OIDC tokens and .well-known/openid-configuration
    # 
    # SOLUTION: Use external domain for hostname, but skip validation for internal requests
    # - Browser access: Via Traefik HTTPS (X-Forwarded-Host: keycloak.orch-XX-XX.pid.infra-host.com)
    #   → Keycloak returns issuer: https://keycloak.orch-XX-XX.pid.infra-host.com/realms/master
    # - Internal services (Vault): Plain HTTP to service DNS (no X-Forwarded-Host)
    #   → Keycloak returns issuer: https://keycloak.orch-XX-XX.pid.infra-host.com/realms/master (SAME!)
    #
    # The trick: Internal services MUST be able to validate this external URL even from inside cluster
    # This works because:
    # 1. Services inside the cluster can reach external URLs via the cluster's network routing
    # 2. The OIDC discovery endpoint just needs to respond with valid JSON
    # 3. Vault validates the discovered issuer URL can serve OIDC tokens
    #
    # NOTE: Set to external domain so browsers get proper cookies and redirect URIs work
    - name: hostname
      value: "https://keycloak.{{ .Values.argo.clusterDomain }}"
    - name: hostname-admin
      value: "https://keycloak.{{ .Values.argo.clusterDomain }}"
    # Read X-Forwarded-* headers from Traefik for correct hostname in OAuth flows
    - name: proxy
      value: "xforwarded"
    # Accept requests from any hostname (Traefik adds X-Forwarded-Host header)
    - name: hostname-strict
      value: "false"
    # For backchannel requests (like OIDC token validation), don't require HTTPS
    - name: hostname-strict-https
      value: "false"
    - name: db-url-properties
      value: "?tcpKeepAlives=true&socketTimeout=120&connectTimeout=120"
    - name: http-management-port
      value: "9000"
    - name: spi-login-protocol-openid-connect-legacy-logout-redirect-uri
      value: "true"
    - name: spi-brute-force-protector-default-brute-force-detector-allow-concurrent-requests
      value: "true"
    - name: log-level
      value: "INFO"
    - name: log-console-output
      value: "json"
  
  instances: 1
  
  # Init container + security hardening
  unsupported:
    podTemplate:
      spec:
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          seccompProfile:
            type: RuntimeDefault
        
        # Init container with ONLY valid build options
        initContainers:
          - name: keycloak-builder
            image: quay.io/keycloak/keycloak:26.4.5
            imagePullPolicy: IfNotPresent
            command: ["/bin/bash"]
            args:
              - -c
              - |
                set -e
                echo "Starting Keycloak build process..."
                
                # Use ONLY valid build-time options
                /opt/keycloak/bin/kc.sh build \
                  --db=postgres \
                  --health-enabled=true \
                  --metrics-enabled=true \
                  --http-relative-path=/
                
                echo "Build completed successfully!"
                echo "Copying built artifacts to shared volume..."
                
                mkdir -p /shared/keycloak
                cp -r /opt/keycloak/* /shared/keycloak/
                
                echo "✅ Keycloak build and copy completed successfully!"
            
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              runAsNonRoot: true
              runAsUser: 1000
              runAsGroup: 1000
              capabilities:
                drop:
                  - ALL
              seccompProfile:
                type: RuntimeDefault
            
            volumeMounts:
              - name: shared-keycloak
                mountPath: /shared/keycloak
              - name: tmp
                mountPath: /tmp
            
            resources:
              requests:
                cpu: 500m
                memory: 512Mi
              limits:
                cpu: 1500m
                memory: 1Gi
        
        # Main container with read-only filesystem
        containers:
          - name: keycloak
            imagePullPolicy: IfNotPresent
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true  # ✅ Security compliant!
              runAsNonRoot: true
              runAsUser: 1000
              runAsGroup: 1000
              capabilities:
                drop:
                  - ALL
              seccompProfile:
                type: RuntimeDefault
            
            volumeMounts:
              - name: shared-keycloak
                mountPath: /opt/keycloak
                readOnly: true
              - name: tmp
                mountPath: /tmp
              - name: keycloak-data
                mountPath: /opt/keycloak/data
        
        volumes:
          - name: shared-keycloak
            emptyDir:
              sizeLimit: 1Gi
          - name: tmp
            emptyDir:
              sizeLimit: 100Mi
          - name: keycloak-data
            emptyDir:
              sizeLimit: 500Mi
