# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

# This is an alias service that provides DNS access from orch-platform namespace
# to the Keycloak service in keycloak-system namespace.
# This allows downstream applications to access Keycloak at:
#   http://platform-keycloak.orch-platform.svc.cluster.local (port 80, default HTTP)
# which resolves to:
#   http://platform-keycloak.keycloak-system.svc.cluster.local (port 80)
#
# This uses an ExternalName service for clean DNS resolution.

apiVersion: v1
kind: Service
metadata:
  name: platform-keycloak
  namespace: orch-platform
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: platform-keycloak
    app.kubernetes.io/version: "26.4.5"
    app.kubernetes.io/component: alias
  annotations:
    description: "ExternalName service providing DNS alias to keycloak-system/platform-keycloak"
    # trivy:ignore:AVD-KSV-0108 This uses ExternalName (not externalIPs), which is NOT vulnerable to CVE-2020-8554
spec:
  type: ExternalName
  externalName: platform-keycloak.keycloak-system.svc.cluster.local
  ports:
    - name: http
      port: 80
      protocol: TCP
