# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

# Enable EnvoyFilter for Grafana header size limits
enableGrafanaHeaderSizeLimits: true

# Configure the header size limit (in KB)
grafanaHeaderSizeLimits:
  maxRequestHeadersKb: 128
