# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-keycloak-config
  namespace: orch-platform
data:
  realm-master.json: |
    {
      "realm": "master",
      "accountTheme": "keycloak",
      "displayName": "Keycloak",
      "displayNameHtml": "<img src='https://raw.githubusercontent.com/open-edge-platform/orch-utils/73df5d1e99a81ae333d94b1c47dd9bef7fa03ae9/keycloak/one-edge-platform-login-title.png'></img>",
      "defaultSignatureAlgorithm": "PS512",
      "accessTokenLifespan": 3600,
      "ssoSessionIdleTimeout": 5400,
      "ssoSessionMaxLifespan": 43200,
      "passwordPolicy": "length(14) and digits(1) and specialChars(1) and upperCase(1) and lowerCase(1)",
      "bruteForceProtected": true,
      "permanentLockout": false,
      "maxFailureWaitSeconds": 900,
      "minimumQuickLoginWaitSeconds": 60,
      "waitIncrementSeconds": 300,
      "quickLoginCheckMilliSeconds": 200,
      "maxDeltaTimeSeconds": 43200,
      "failureFactor": 5,
      "roles": {
        "realm": [
          {
            "name": "en-agent-rw"
          },
          {
            "name": "secrets-root-role"
          },
          {
            "name": "rs-access-r"
          },
          {
            "name": "rs-proxy-r"
          },
          {
            "name": "app-service-proxy-read-role"
          },
          {
            "name": "app-service-proxy-write-role"
          },
          {
            "name": "app-deployment-manager-read-role"
          },
          {
            "name": "app-deployment-manager-write-role"
          },
          {
            "name": "app-resource-manager-read-role"
          },
          {
            "name": "app-resource-manager-write-role"
          },
          {
            "name": "app-vm-console-write-role"
          },
          {
            "name": "catalog-publisher-read-role"
          },
          {
            "name": "catalog-publisher-write-role"
          },
          {
            "name": "catalog-other-read-role"
          },
          {
            "name": "catalog-other-write-role"
          },
          {
            "name": "catalog-restricted-read-role"
          },
          {
            "name": "catalog-restricted-write-role"
          },
          {
            "name": "clusters-read-role"
          },
          {
            "name": "clusters-write-role"
          },
          {
            "name": "cluster-templates-read-role"
          },
          {
            "name": "cluster-templates-write-role"
          },
          {
            "name": "cluster-artifacts-read-role"
          },
          {
            "name": "cluster-artifacts-write-role"
          },
          {
            "name": "infra-manager-core-read-role"
          },
          {
            "name": "infra-manager-core-write-role"
          },
          {
            "name": "alrt-r"
          },
          {
            "name": "alrt-rw"
          },
          {
            "name": "alrt-rx-rw"
          },
          {
            "name": "ao-m2m-rw"  
          },
          {
            "name": "co-m2m-rw"
          },
          {
            "name": "org-read-role"
          },
          {
            "name": "org-write-role"
          },
          {
            "name": "org-update-role"
          },
          {
            "name": "org-delete-role"
          }
        ],
        "client": {
          "alerts-m2m-client": [],
          "host-manager-m2m-client": [],
          "ktc-m2m-client": [],
          "3rd-party-host-manager-m2m-client": [],
          "edge-manager-m2m-client": [],
          "en-m2m-template-client": [],
          "webui-client": [],
          "docsui-client": [],
          "account": [
            {
              "name": "view-profile",
              "clientRole": true
            },
            {
              "name": "manage-account",
              "clientRole": true
            }
          ],
          "telemetry-client": [
            {
              "name": "admin",
              "clientRole": true
            },
            {
              "name": "viewer",
              "clientRole": true
            }
          ],
          "cluster-management-client": [
            {
              "name": "restricted-role",
              "clientRole": true
            },
            {
              "name": "standard-role",
              "clientRole": true
            },
            {
              "name": "base-role",
              "clientRole": true
            }
          ],
          "registry-client": [
            {
              "name": "registry-admin-role",
              "clientRole": true
            },
            {
              "name": "registry-editor-role",
              "clientRole": true
            },
            {
              "name": "registry-viewer-role",
              "clientRole": true
            }
          ]
        }
      },
      "clients": [
        {
          "clientId": "alerts-m2m-client",
          "name": "Alerts M2M Client",
          "description": "Client for Alerts",
          "surrogateAuthRequired": false,
          "enabled": true,
          "alwaysDisplayInConsole": false,
          "clientAuthenticatorType": "client-secret",
          "notBefore": 0,
          "bearerOnly": false,
          "consentRequired": false,
          "standardFlowEnabled": false,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": false,
          "serviceAccountsEnabled": true,
          "authorizationServicesEnabled": true,
          "publicClient": false,
          "protocol": "openid-connect",
          "attributes": {
            "oidc.ciba.grant.enabled": "false",
            "oauth2.device.authorization.grant.enabled": "false",
            "backchannel.logout.revoke.offline.tokens": "false"
          },
          "fullScopeAllowed": true,
          "defaultClientScopes": [
            "web-origins",
            "acr",
            "profile",
            "roles",
            "email",
            "basic"
          ],
          "optionalClientScopes": [
            "address",
            "phone",
            "offline_access",
            "microprofile-jwt"
          ]
        },
        {
          "clientId": "system-client",
          "name": "System Client",
          "surrogateAuthRequired": false,
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "redirectUris": [],
          "webOrigins": [],
          "standardFlowEnabled": false,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": true,
          "serviceAccountsEnabled": false,
          "publicClient": true,
          "frontchannelLogout": true,
          "protocol": "openid-connect",
          "attributes": {
            "oidc.ciba.grant.enabled": "false",
            "oauth2.device.authorization.grant.enabled": "true",
            "backchannel.logout.session.required": "true",
            "backchannel.logout.revoke.offline.tokens": "false"
          },
          "fullScopeAllowed": true,
          "defaultClientScopes": [
            "roles",
            "profile",
            "email",
            "basic"
          ],
          "optionalClientScopes": [
            "groups",
            "offline_access"
          ]
        }
      ],
      "clientScopes": [
        {
          "name": "groups",
          "description": "Groups scope",
          "type": "Optional",
          "protocol": "openid-connect",
          "attributes": {
            "include.in.token.scope": "true",
            "display.on.consent.screen": "true"
          },
          "protocolMappers": [
            {
              "name": "groups",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-group-membership-mapper",
              "consentRequired": false,
              "config": {
                "multivalued": "true",
                "full.path": "false",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "groups",
                "userinfo.token.claim": "true",
                "jsonType.label": "String"
              }
            }
          ]
        }
      ],
      "groups": [
        {
          "name": "apps-m2m-service-account",
          "path": "/apps-m2m-service-account",
          "realmRoles": [
            "ao-m2m-rw",
            "co-m2m-rw"
          ]
        },
        {
          "name": "edge-manager-group",
          "path": "/edge-manager-group",
          "realmRoles": [
            "app-service-proxy-read-role",
            "app-service-proxy-write-role",
            "app-deployment-manager-read-role",
            "app-deployment-manager-write-role"
          ]
        }
      ],
      "users": [
        {
          "username": "service-account-alerts-m2m-client",
          "enabled": true,
          "totp": false,
          "serviceAccountClientId": "alerts-m2m-client",
          "realmRoles": [
            "default-roles-master"
          ],
          "clientRoles": {
            "alerts-m2m-client": [
              "uma_protection"
            ]
          },
          "notBefore": 0
        }
      ],
      "components": {
        "org.keycloak.keys.KeyProvider": [
          {
            "name": "fallback-PS512",
            "providerId": "rsa-generated",
            "subComponents": {},
            "config": {
              "keySize": [
                "4096"
              ],
              "active": [
                "true"
              ],
              "priority": [
                "-100"
              ],
              "enabled": [
                "true"
              ],
              "algorithm": [
                "PS512"
              ]
            }
          }
        ]
      }
    }