# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

# Template for creating the Keycloak database secret
# This secret contains the PostgreSQL connection information for Keycloak
# 
# IMPORTANT: Update the values below to match your environment before applying!
#
# For local deployment, the secret is typically created by mage commands
# For production, ensure you have the correct database connection details

apiVersion: v1
kind: Secret
metadata:
  name: platform-keycloak-local-postgresql
  namespace: orch-platform  # Update to your actual namespace
type: Opaque
stringData:
  # Database connection details - UPDATE THESE VALUES!
  PGHOST: postgresql.orch-database.svc.cluster.local  # PostgreSQL service name
  PGPORT: "5432"                                      # PostgreSQL port
  PGUSER: orch-platform-keycloak_user                 # Database username
  PGDATABASE: orch-platform-keycloak                  # Database name
  PGPASSWORD: your-database-password-here             # Database password - CHANGE THIS!
  
  # Additional fields that might be used
  password: your-database-password-here               # Alternative password field