# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: batch/v1
kind: Job
metadata:
  name: platform-keycloak-config-import
  namespace: orch-platform
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: hook-succeeded
    # Security annotations for image registry approval
    security.approved-registries: "quay.io"
    security.image-purpose: "keycloak-config-cli for realm configuration import"
    security.image-vendor: "adorsys/keycloak-config-cli"
    security.image-verification: "official-keycloak-tooling"
spec:
  template:
    metadata:
      labels:
        app: keycloak-config-import
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: "RuntimeDefault"
      containers:
        - name: keycloak-config-cli
          image: quay.io/adorsys/keycloak-config-cli:6.1.4-26.0.2
          imagePullPolicy: IfNotPresent
          env:
            - name: KEYCLOAK_URL
              value: "http://platform-keycloak-http.orch-platform.svc.cluster.local:8080"
            - name: KEYCLOAK_USER
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: platform-keycloak
                  key: admin-password
            - name: IMPORT_MANAGED_GROUP
              value: "no-delete"
            - name: IMPORT_MANAGED_REQUIRED_ACTION
              value: "no-delete"
            - name: IMPORT_MANAGED_ROLE
              value: "no-delete"
            - name: IMPORT_MANAGED_CLIENT
              value: "no-delete"
            - name: KEYCLOAK_AVAILABILITYCHECK_ENABLED
              value: "true"
            - name: KEYCLOAK_AVAILABILITYCHECK_TIMEOUT
              value: "120s"
          volumeMounts:
            - name: keycloak-config
              mountPath: /opt/keycloak-config-cli/configs
              readOnly: true
            - name: tmp-volume
              mountPath: /tmp
            - name: var-tmp-volume
              mountPath: /var/tmp
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: "RuntimeDefault"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: keycloak-config
          configMap:
            name: platform-keycloak-config
        - name: tmp-volume
          emptyDir: {}
        - name: var-tmp-volume
          emptyDir: {}
