# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

namespace: orch-database

annotations:
  cnpg.io/reload: "false"

host: "postgresql-cluster-rw.orch-database"
