# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

containersecuritycontext:
  allowprivilegeescalation: false
server:
  image:
    tag: "1.20.4"
    # Overrides the default Image Pull Policy
    pullPolicy: IfNotPresent

  # Configure the logging verbosity for the Vault server.
  # Supported log levels include: trace, debug, info, warn, error
  logLevel: "info"

  # This configures the Vault Statefulset to create a PVC for data
  # storage when using the file or raft backend storage engines.
  # See https://www.vaultproject.io/docs/configuration/storage/index.html to know more
  dataStorage:
    # PVC not needed when using Postgres storage backend
    enabled: false

  # volumes is a list of volumes made available to all containers. These are rendered
  # via toYaml rather than pre-processed like the extraVolumes value.
  # The purpose is to make it easy to share volumes between containers.
  volumes:
    - name: vault-storage-config
      emptyDir: {}

  # volumeMounts is a list of volumeMounts for the main server container. These are rendered
  # via toYaml rather than pre-processed like the extraVolumes value.
  # The purpose is to make it easy to share volumes between containers.
  volumeMounts:
    - mountPath: /vault/userconfig/vault-storage-config
      name: vault-storage-config
      readOnly: true

  extraArgs: "-config=/vault/userconfig/vault-storage-config/storage.hcl"
  # Settings for the statefulSet used to run Vault.
  statefulSet:
    # Set the pod and container security contexts.
    # If not set, these will default to, and for *not* OpenShift:
    # pod:
    #   runAsNonRoot: true
    #   runAsGroup: {{ .Values.server.gid | default 1000 }}
    #   runAsUser: {{ .Values.server.uid | default 100 }}
    #   fsGroup: {{ .Values.server.gid | default 1000 }}
    # container:
    #   allowPrivilegeEscalation: false
    #
    securityContext:
      container:
        capabilities:
          drop:
            - ALL
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
  resources: null

injector:
  strategy:
    type: Recreate
  securityContext:
    container:
      capabilities:
        drop:
          - ALL
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
  resources: null
