# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

# This patch applies strict security contexts to the Keycloak Operator deployment
# to comply with restricted Kubernetes PodSecurity policies

apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-operator
spec:
  template:
    spec:
      # Pod-level security context
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: keycloak-operator
        # Container-level security context
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
        # Add volumeMounts for writable directories if needed by the operator
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: var-cache
          mountPath: /var/cache
      # Add emptyDir volumes for temporary storage
      volumes:
      - name: tmp
        emptyDir: {}
      - name: var-cache
        emptyDir: {}
