
name: Bug report
description: Create an issue to help us improve
title: '[BUG] <Software> - <Summary>'
labels: ['BUG','TRIAGE']
body:
  - type: markdown
    attributes:
      value: <br>To expedite issue processing please search open and closed issues before submitting a new one. Existing issues often contain information about workarounds, resolution, or progress updates.

  - type: textarea
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Type
      description: Select the type of issue
      options:
        - label: Bug
          description: A defect or error in the software
        - label: Epic
          description: A large body of work that can be broken down into smaller tasks
        - label: Feature
          description: A new capability or enhancement to the software
        - label: Task
          description: A standalone piece of work to be completed
    validations:
      required: true

  - type: textarea
    attributes:
      label: System Setup
      description: Describe your system and software setup.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproducible Steps
      description: Describe how we can reproduce your issue.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Root Cause Analysis
      description: Provide any initial triage, if possible.
