blank_issues_enabled: false
contact_links:
  - name: Open Edge Platform Support
    url: https://github.com/open-edge-platform/edge-manageability-framework/discussions
    about: Please ask and answer questions here.