name: Feature Request
description: File a feature request. 
title: '[FEATURE]: '
labels: ['feature']
type: "Feature"
body:
  - type: textarea
    attributes:
      label: Feature Description
      description: A clear and concise description of the problem or missing capability. 
    validations:
      required: true
  - type: input
    attributes:
      label: Current Software Version
      description: |
        What version are you currently using? This helps us understand your context and avoid suggesting features that may already exist in newer versions.
      placeholder: v1.2.0 / main branch / tag v2025.2.0-rc3
    validations:
      required: false
  - type: textarea
    attributes:
      label: Solution Description
      description: If you have a solution in mind, please describe it.

  - type: textarea
    attributes:
      label: Alternative Description
      description: Have you considered any alternative solutions or workarounds?
