namespace: orch-database

type: postgresql
mode: standalone

version:
  postgresql: "17"

cluster:
  instances: 1

  storage:
    size: "8Gi"

  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "384Mi"
      cpu: "375m"

  postgresql:
    parameters:
      huge_pages: "off"
      max_connections: "200"
      shared_buffers: "24MB"

  initdb:
    database: postgres
    owner: orch-database-postgresql_user
    localeCType: "en_US.UTF-8"
    localeCollate: "en_US.UTF-8"
    secret:
      name: "orch-database-postgresql"
