apiVersion: v1
kind: Service
metadata:
  name: platform-keycloak
  namespace: orch-platform
  labels:
    app.kubernetes.io/instance: platform-keycloak
    app.kubernetes.io/name: keycloakx
    app.kubernetes.io/component: http
  annotations:
    # Compatibility alias for platform-keycloak-http
    platform.open-edge/managed-by: "legacy-service-alias"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: platform-keycloak
    app.kubernetes.io/name: keycloakx
  ports:
    - name: http-internal
      port: 9000
      protocol: TCP
      targetPort: http-internal
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
