# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: "Deploy on Prem Orchestrator"
description: "Creates a VM and Deploys the Orchestrator on it"
inputs:
  orch_version:
    required: false
    description: "Orchestrator version to deploy"
    default: "main"
  orch_profile:
    required: false
    description: "Orchestrator profile to deploy"
    default: "onprem"
  docker_username:
    required: true
    description: "Docker Hub username for pulling images"
  docker_password:
    required: true
    description: "Docker Hub password for pulling images"

runs:
  using: "composite"
  steps:
    - name: Checkout Orchestrator repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      with:
        repository: open-edge-platform/edge-manageability-framework
        ref: ${{ inputs.orch_version }}
        persist-credentials: false

    - name: Setup asdf and install dependencies
      id: install-deps
      uses: open-edge-platform/orch-utils/.github/actions/setup-asdf@main  # zizmor: ignore[unpinned-uses]

    - name: Check Oras
      run: |
        oras version
      shell: bash

    - name: Set deploy tag
      id: deploy-tag
      shell: bash
      working-directory: on-prem-installers
      # NOTE: The terraform deploy tag is different than the git ref, it's calucated using this mage target
      run: |
        mage build:debVersion
        DEPLOY_TAG=$(mage build:debVersion)
        DEPLOY_TAG="${DEPLOY_TAG//[$'\r\n']}"
        echo "deploy_tag=${DEPLOY_TAG}" >> "$GITHUB_OUTPUT"

    - name: Deploy Orchestrator
      env:
        TF_VAR_deploy_tag: ${{ steps.deploy-tag.outputs.deploy_tag }}
        TF_VAR_orch_profile: ${{ inputs.orch_profile }}
        TF_VAR_FILE: ${{ github.workspace }}/terraform/orchestrator/terraform.tfvars
        TF_VAR_docker_username: ${{ inputs.docker_username }}
        TF_VAR_docker_password: ${{ inputs.docker_password }}
        KUBECONFIG: ${{ github.workspace }}/terraform/orchestrator/files/kubeconfig
      shell: bash
      run: mage deploy:onPrem

    - name: Verify deployment
      shell: bash
      env:
        KUBECONFIG: ${{ github.workspace }}/terraform/orchestrator/files/kubeconfig
      run: mage -v deploy:waitUntilComplete

    - name: Setup test environment
      shell: bash
      env:
        KUBECONFIG: ${{ github.workspace }}/terraform/orchestrator/files/kubeconfig
      run: mage -v gen:orchCA deploy:orchCA deploy:edgeNetworkDNS

    - name: Get diagnostic information
      id: get-diagnostic-info
      if: always() && steps.install-deps.conclusion == 'success'
      env:
        SSH_HOST: 192.168.99.10
        SSH_USER: ubuntu
        SSH_PASSWORD: ubuntu
        KUBECONFIG: ${{ github.workspace }}/terraform/orchestrator/files/kubeconfig        
        ORCH_PROFILE: ${{ inputs.orch_profile }}
      shell: bash
      run: |
        mkdir -p "$ORCH_PROFILE-diagnostics"
        kubectl config set-cluster default --server="https://${SSH_HOST}:6443" --insecure-skip-tls-verify
        
        # Pod information
        kubectl get pods -o wide -A > "$ORCH_PROFILE-diagnostics/pods-list.txt"
        kubectl describe pods -A > "$ORCH_PROFILE-diagnostics/pods-describe.txt"
        
        # Gitea-specific diagnostics
        echo "=== Gitea Namespace Status ===" > "$ORCH_PROFILE-diagnostics/gitea-diagnostics.txt"
        kubectl get pods -n gitea -o wide >> "$ORCH_PROFILE-diagnostics/gitea-diagnostics.txt" 2>&1 || true
        echo "" >> "$ORCH_PROFILE-diagnostics/gitea-diagnostics.txt"
        echo "=== Gitea Pod Describe ===" >> "$ORCH_PROFILE-diagnostics/gitea-diagnostics.txt"
        kubectl describe pods -n gitea >> "$ORCH_PROFILE-diagnostics/gitea-diagnostics.txt" 2>&1 || true
        echo "" >> "$ORCH_PROFILE-diagnostics/gitea-diagnostics.txt"
        echo "=== Gitea Pod Logs ===" >> "$ORCH_PROFILE-diagnostics/gitea-diagnostics.txt"
        kubectl logs -n gitea --all-containers=true --tail=500 >> "$ORCH_PROFILE-diagnostics/gitea-diagnostics.txt" 2>&1 || true
        echo "" >> "$ORCH_PROFILE-diagnostics/gitea-diagnostics.txt"
        echo "=== Gitea PVC Status ===" >> "$ORCH_PROFILE-diagnostics/gitea-diagnostics.txt"
        kubectl get pvc -n gitea -o wide >> "$ORCH_PROFILE-diagnostics/gitea-diagnostics.txt" 2>&1 || true
        echo "" >> "$ORCH_PROFILE-diagnostics/gitea-diagnostics.txt"
        echo "=== Gitea PV Status ===" >> "$ORCH_PROFILE-diagnostics/gitea-diagnostics.txt"
        kubectl get pv -o wide >> "$ORCH_PROFILE-diagnostics/gitea-diagnostics.txt" 2>&1 || true
        
        # ArgoCD diagnostics
        mage logutils:collectArgoDiags > "$ORCH_PROFILE-diagnostics/argo-diag.txt" 2>&1 || true
        kubectl get applications -o yaml -A > "$ORCH_PROFILE-diagnostics/argocd-applications.yaml"
        
        # Gitea ArgoCD Application status
        echo "=== Gitea ArgoCD Application Status ===" > "$ORCH_PROFILE-diagnostics/argocd-gitea-app.txt"
        kubectl get application gitea -n argocd -o yaml >> "$ORCH_PROFILE-diagnostics/argocd-gitea-app.txt" 2>&1 || true
        echo "" >> "$ORCH_PROFILE-diagnostics/argocd-gitea-app.txt"
        echo "=== Gitea ArgoCD AppProject Status ===" >> "$ORCH_PROFILE-diagnostics/argocd-gitea-app.txt"
        kubectl get appproject -n argocd -o yaml >> "$ORCH_PROFILE-diagnostics/argocd-gitea-app.txt" 2>&1 || true
        
        # Cluster events
        kubectl get events -o yaml -A > "$ORCH_PROFILE-diagnostics/events.yaml"
        
        # Storage class diagnostics
        echo "=== Storage Classes ===" > "$ORCH_PROFILE-diagnostics/storage-diagnostics.txt"
        kubectl get storageclass -o wide >> "$ORCH_PROFILE-diagnostics/storage-diagnostics.txt" 2>&1 || true
        echo "" >> "$ORCH_PROFILE-diagnostics/storage-diagnostics.txt"
        echo "=== OpenEBS Pods ===" >> "$ORCH_PROFILE-diagnostics/storage-diagnostics.txt"
        kubectl get pods -n openebs-system -o wide >> "$ORCH_PROFILE-diagnostics/storage-diagnostics.txt" 2>&1 || true
        
        # Network and proxy diagnostics (especially important for OXM profiles)
        echo "=== Network Policies ===" > "$ORCH_PROFILE-diagnostics/network-diagnostics.txt"
        kubectl get networkpolicies -A -o yaml >> "$ORCH_PROFILE-diagnostics/network-diagnostics.txt" 2>&1 || true
        echo "" >> "$ORCH_PROFILE-diagnostics/network-diagnostics.txt"
        echo "=== Gitea Pod Network Status ===" >> "$ORCH_PROFILE-diagnostics/network-diagnostics.txt"
        kubectl exec -n gitea -c gitea $(kubectl get pods -n gitea -l app=gitea -o jsonpath='{.items[0].metadata.name}' 2>/dev/null) -- bash -c "env | grep -i proxy; echo '---'; ip addr; echo '---'; netstat -tlnp 2>/dev/null || ss -tlnp" >> "$ORCH_PROFILE-diagnostics/network-diagnostics.txt" 2>&1 || echo "Could not get pod network info" >> "$ORCH_PROFILE-diagnostics/network-diagnostics.txt"
        echo "" >> "$ORCH_PROFILE-diagnostics/network-diagnostics.txt"
        echo "=== DNS Resolution in Gitea Pod ===" >> "$ORCH_PROFILE-diagnostics/network-diagnostics.txt"
        kubectl exec -n gitea -c gitea $(kubectl get pods -n gitea -l app=gitea -o jsonpath='{.items[0].metadata.name}' 2>/dev/null) -- bash -c "cat /etc/resolv.conf; echo '---'; nslookup dl.gitea.com; echo '---'; curl -I https://dl.gitea.com/charts/ 2>&1 | head -20" >> "$ORCH_PROFILE-diagnostics/network-diagnostics.txt" 2>&1 || echo "Could not resolve DNS" >> "$ORCH_PROFILE-diagnostics/network-diagnostics.txt"
        
        # OXM-specific proxy configuration check
        if [[ "$ORCH_PROFILE" == "onprem-oxm" ]]; then
          echo "=== OXM Proxy Configuration ===" >> "$ORCH_PROFILE-diagnostics/network-diagnostics.txt"
          echo "TF_VAR_en_http_proxy: ${TF_VAR_en_http_proxy:-not set}" >> "$ORCH_PROFILE-diagnostics/network-diagnostics.txt"
          echo "TF_VAR_en_https_proxy: ${TF_VAR_en_https_proxy:-not set}" >> "$ORCH_PROFILE-diagnostics/network-diagnostics.txt"
          echo "TF_VAR_no_proxy: ${TF_VAR_no_proxy:-not set}" >> "$ORCH_PROFILE-diagnostics/network-diagnostics.txt"
          echo "" >> "$ORCH_PROFILE-diagnostics/network-diagnostics.txt"
        fi
        
        # OS/System level diagnostics
        echo "=== System Information ===" > "$ORCH_PROFILE-diagnostics/system-diagnostics.txt"
        uname -a >> "$ORCH_PROFILE-diagnostics/system-diagnostics.txt" 2>&1 || true
        echo "" >> "$ORCH_PROFILE-diagnostics/system-diagnostics.txt"
        echo "=== Disk Usage ===" >> "$ORCH_PROFILE-diagnostics/system-diagnostics.txt"
        df -h >> "$ORCH_PROFILE-diagnostics/system-diagnostics.txt" 2>&1 || true
        echo "" >> "$ORCH_PROFILE-diagnostics/system-diagnostics.txt"
        echo "=== Memory Usage ===" >> "$ORCH_PROFILE-diagnostics/system-diagnostics.txt"
        free -h >> "$ORCH_PROFILE-diagnostics/system-diagnostics.txt" 2>&1 || true
        echo "" >> "$ORCH_PROFILE-diagnostics/system-diagnostics.txt"
        echo "=== CPU Info ===" >> "$ORCH_PROFILE-diagnostics/system-diagnostics.txt"
        nproc >> "$ORCH_PROFILE-diagnostics/system-diagnostics.txt" 2>&1 || true
        
        # DEB package and installation diagnostics
        echo "=== DEB Package Status ===" > "$ORCH_PROFILE-diagnostics/dpkg-diagnostics.txt"
        dpkg -l | grep -E "onprem|gitea|argo" >> "$ORCH_PROFILE-diagnostics/dpkg-diagnostics.txt" 2>&1 || true
        echo "" >> "$ORCH_PROFILE-diagnostics/dpkg-diagnostics.txt"
        echo "=== Failed DEB Packages ===" >> "$ORCH_PROFILE-diagnostics/dpkg-diagnostics.txt"
        dpkg --get-selections | grep -i hold >> "$ORCH_PROFILE-diagnostics/dpkg-diagnostics.txt" 2>&1 || true
        echo "" >> "$ORCH_PROFILE-diagnostics/dpkg-diagnostics.txt"
        echo "=== APT Error Log ===" >> "$ORCH_PROFILE-diagnostics/dpkg-diagnostics.txt"
        sudo cat /var/log/apt/term.log >> "$ORCH_PROFILE-diagnostics/dpkg-diagnostics.txt" 2>&1 || true
        echo "" >> "$ORCH_PROFILE-diagnostics/dpkg-diagnostics.txt"
        echo "=== Cloud-init Output ===" >> "$ORCH_PROFILE-diagnostics/dpkg-diagnostics.txt"
        sudo cat /var/log/cloud-init-output.log >> "$ORCH_PROFILE-diagnostics/dpkg-diagnostics.txt" 2>&1 || tail -200 /var/log/cloud-init-output.log >> "$ORCH_PROFILE-diagnostics/dpkg-diagnostics.txt" 2>&1 || true
        echo "" >> "$ORCH_PROFILE-diagnostics/dpkg-diagnostics.txt"
        echo "=== Systemd Journal (Helm/Installer errors) ===" >> "$ORCH_PROFILE-diagnostics/dpkg-diagnostics.txt"
        sudo journalctl -xe --no-pager | tail -300 >> "$ORCH_PROFILE-diagnostics/dpkg-diagnostics.txt" 2>&1 || true

    - name: Upload diagnostic information to CI artifact store
      if: always() && steps.get-diagnostic-info.conclusion == 'success'
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
      with:
        name: ${{ inputs.orch_profile }}-diagnostics
        path: |
          ${{ inputs.orch_profile }}-diagnostics/pods-list.txt
          ${{ inputs.orch_profile }}-diagnostics/pods-describe.txt
          ${{ inputs.orch_profile }}-diagnostics/gitea-diagnostics.txt
          ${{ inputs.orch_profile }}-diagnostics/argocd-gitea-app.txt
          ${{ inputs.orch_profile }}-diagnostics/argo-diag.txt
          ${{ inputs.orch_profile }}-diagnostics/argocd-applications.yaml
          ${{ inputs.orch_profile }}-diagnostics/events.yaml
          ${{ inputs.orch_profile }}-diagnostics/storage-diagnostics.txt
          ${{ inputs.orch_profile }}-diagnostics/network-diagnostics.txt
          ${{ inputs.orch_profile }}-diagnostics/system-diagnostics.txt
          ${{ inputs.orch_profile }}-diagnostics/dpkg-diagnostics.txt
