# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

# Default values for platform-keycloak chart
# This chart manages the Keycloak instance deployment and configuration
# Note: Operator installation is handled by the separate platform-keycloak-operator chart

# Keycloak instance configuration
keycloak:
  enabled: true
  instanceName: platform-keycloak
  instanceNamespace: orch-platform
  instances: 1
  
  # Bootstrap admin credentials from the secret created by deploy.go
  # The operator expects a secret with 'username' and 'password' keys
  bootstrapAdmin:
    user:
      secret: platform-keycloak
  
  # Hostname configuration
  hostname:
    strict: false
    
  # HTTP configuration
  http:
    httpEnabled: true
    httpPort: 8080
    
  # Proxy configuration
  proxy:
    headers: xforwarded
    
  # Database configuration
  db:
    vendor: postgres
    host: postgresql.orch-database.svc.cluster.local
    port: 5432
    database: orch-platform-platform-keycloak
    usernameSecret:
      name: platform-keycloak-local-postgresql
      key: PGUSER
    passwordSecret:
      name: platform-keycloak-local-postgresql
      key: PGPASSWORD
      
  # Resource limits for Keycloak pods
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
      
  # Additional Keycloak options (environment variables)
  additionalOptions:
    - name: KC_PROXY_HEADERS
      value: xforwarded
    - name: KC_HOSTNAME_STRICT
      value: "false"
    - name: KC_HOSTNAME_STRICT_HTTPS
      value: "false"
  
  # Ingress configuration (disabled by default, use Istio)
  ingress:
    enabled: false
    
  # Network policy configuration
  networkPolicy:
    enabled: false

# Service alias for backward compatibility
service:
  enabled: true
  name: platform-keycloak
  namespace: orch-platform
  targetService: platform-keycloak-service
  targetNamespace: orch-platform
  port: 8080

# Configuration CLI for realm setup
configCli:
  enabled: true
  # Image for config bootstrap job
  image: curlimages/curl:8.4.0
  # Authentication using the platform-keycloak secret
  auth:
    secretName: platform-keycloak
    usernameKey: username
    passwordKey: password
  # Resources for config job
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  # Realm configuration files
  configuration:
    realm-master.json: |
      {
        "realm": "master",
        "accountTheme": "keycloak",
        "displayName": "Keycloak"
      }
