acmImportIfNotExists: "false"
awsR35Domain: orch-10-114-181-164.espdqa.infra-host.com
certDomain: onprem
image:
  registry: registry-rs.edgeorchestration.intel.com/edge-orch
  repository: common/cert-synchronizer
proxy:
  httpProxy: http://proxy-dmz.intel.com:912
  httpsProxy: http://proxy-dmz.intel.com:912
  noProxy: .caas.intel.com,certificates.intel.com,localhost,127.0.0.0/8,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,169.254.169.254,.svc,.cluster.local,.default,.internal,.orch-platform,.orch-app,.orch-cluster,.orch-infra,.orch-database,.cattle-system,.orch-secret,.onprem,.espd.infra-host.com,.pid.infra-host.com,.espdqa.infra-host.com
resources: null
