externalSecretsApiGroup: external-secrets.io/v1
keyName:
  - source: admin-password
    target: admin-password
  - source: password
    target: password
  - source: username
    target: username
refreshInterval: 0m
remoteNamespace: orch-platform
sourceSecretName: platform-keycloak
targetSecretName: platform-keycloak
