externalSecretsApiGroup: external-secrets.io/v1
keyName:
  - source: ca.crt
    target: cacerts.pem
refreshInterval: 10m
remoteNamespace: orch-gateway
sourceSecretName: tls-orch
targetSecretName: tls-ca
