api:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
apiv2:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
attestationstatus-manager:
  image:
    pullPolicy: IfNotPresent
  inventory:
    addr: inventory.orch-infra.svc.cluster.local
  multiTenancy:
    enforceMultiTenancy: "true"
  oidc:
    oidc_server_url: http://platform-keycloak.orch-platform.svc/realms/master
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
  serviceArgs:
    traceURL: orchestrator-observability-opentelemetry-collector.orch-platform.svc:4318
  traefikApiGroup: traefik.io/v1alpha1
  traefikReverseProxy:
    enabled: true
    host:
      grpc:
        name: Host(`attest-node.orch-10-114-181-164.espdqa.infra-host.com`)
    secretName: tls-orch
    tlsOption: gateway-tls
credentialsM2M:
  job:
    resources:
      limits:
        cpu: "64"
        memory: 64Gi
      requests:
        cpu: 1m
        memory: 1Mi
dkam:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
exporter:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
global:
  registry:
    imagePullSecrets: []
    name: registry-rs.edgeorchestration.intel.com/edge-orch/
host-manager:
  disabledProvisioning: false
  image:
    pullPolicy: IfNotPresent
  inventory:
    addr: inventory.orch-infra.svc.cluster.local
  multiTenancy:
    enforceMultiTenancy: "true"
  oidc:
    oidc_server_url: http://platform-keycloak.orch-platform.svc/realms/master
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
  serviceArgs:
    traceURL: orchestrator-observability-opentelemetry-collector.orch-platform.svc:4318
  traefikApiGroup: traefik.io/v1alpha1
  traefikReverseProxy:
    enabled: true
    host:
      grpc:
        name: Host(`infra-node.orch-10-114-181-164.espdqa.infra-host.com`)
    secretName: tls-orch
    tlsOption: gateway-tls
import:
  attestationstatus-manager:
    enabled: true
  host-manager:
    enabled: true
  maintenance-manager:
    enabled: true
  networking-manager:
    enabled: true
  os-resource-manager:
    enabled: true
  telemetry-manager:
    enabled: false
inventory:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
maintenance-manager:
  image:
    pullPolicy: IfNotPresent
  inventory:
    addr: inventory.orch-infra.svc.cluster.local
  mimaintmgr:
    traceURL: orchestrator-observability-opentelemetry-collector.orch-platform.svc:4318
  multiTenancy:
    enforceMultiTenancy: "true"
  oidc:
    oidc_server_url: http://platform-keycloak.orch-platform.svc/realms/master
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
  serviceArgs:
    traceURL: orchestrator-observability-opentelemetry-collector.orch-platform.svc:4318
  telemetryMgrArgs:
    enableVal: false
  traefikApiGroup: traefik.io/v1alpha1
  traefikReverseProxy:
    enabled: true
    host:
      grpc:
        name: Host(`update-node.orch-10-114-181-164.espdqa.infra-host.com`)
    secretName: tls-orch
    tlsOption: gateway-tls
networking-manager:
  image:
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
  serviceArgs:
    inventoryAddress: inventory.orch-infra.svc.cluster.local:50051
    traceURL: orchestrator-observability-opentelemetry-collector.orch-platform.svc:4318
onboarding-manager:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
os-resource-manager:
  autoProvision:
    enabled: false
  image:
    pullPolicy: IfNotPresent
  managerArgs:
    inventoryAddress: inventory.orch-infra.svc.cluster.local:50051
    manualMode: false
    osProfileRevision: 0.10.8
    osSecurityFeatureEnable: false
    rsEnProfileRepo: edge-orch/en/files/os-profile/
    rsProxyFilesAddress: rs-proxy-files.orch-platform.svc.cluster.local:8081/
    rsProxyRegistryAddress: rs-proxy.orch-platform.svc.cluster.local:8081/
    traceURL: orchestrator-observability-opentelemetry-collector.orch-platform.svc:4318
  multiTenancy:
    enforceMultiTenancy: "true"
  oidc:
    oidc_server_url: http://platform-keycloak.orch-platform.svc.cluster.local/realms/master
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
pxe-server:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
resources:
  limits:
    cpu: "64"
    memory: 64Gi
  requests:
    cpu: 1m
    memory: 1Mi
telemetry-manager:
  image:
    pullPolicy: IfNotPresent
  multiTenancy:
    enforceMultiTenancy: "true"
  oidc:
    oidc_server_url: http://platform-keycloak.orch-platform.svc/realms/master
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
  telemetryMgrArgs:
    inventoryAddress: inventory.orch-infra.svc.cluster.local:50051
    traceURL: orchestrator-observability-opentelemetry-collector.orch-platform.svc:4318
  traefikApiGroup: traefik.io/v1alpha1
  traefikReverseProxy:
    enabled: true
    host:
      grpc:
        name: Host(`telemetry-node.orch-10-114-181-164.espdqa.infra-host.com`)
    secretName: tls-orch
    tlsOption: gateway-tls
tenant-controller:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
tinkerbell:
  stack:
    resources:
      limits:
        cpu: "64"
        memory: 64Gi
      requests:
        cpu: 200m
        memory: 256Mi
