api:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
apiv2:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
attestationstatus-manager:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
dkam:
  env:
    mode: prod
    oidc:
      oidc_server_url: http://platform-keycloak.orch-platform.svc/realms/master
    rs_proxy_address: rs-proxy.orch-platform.svc.cluster.local:8081/
  managerArgs:
    enableTracing: false
    traceURL: orchestrator-observability-opentelemetry-collector.orch-platform.svc:4318
  metrics:
    enabled: false
  proxies:
    http_proxy: http://proxy-dmz.intel.com:912
    https_proxy: http://proxy-dmz.intel.com:912
    no_proxy: .caas.intel.com,certificates.intel.com,localhost,127.0.0.0/8,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,169.254.169.254,.svc,.cluster.local,.default,.internal,.orch-platform,.orch-app,.orch-cluster,.orch-infra,.orch-database,.cattle-system,.orch-secret,.onprem,.espd.infra-host.com,.pid.infra-host.com,.espdqa.infra-host.com
  pvc:
    storageClassName: openebs-hostpath
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
exporter:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
global:
  registry:
    imagePullSecrets: []
    name: registry-rs.edgeorchestration.intel.com/edge-orch/
host-manager:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
import:
  dkam:
    enabled: true
  infra-config:
    enabled: true
  onboarding-manager:
    enabled: true
  pxe-server:
    enabled: false
  tinkerbell:
    enabled: true
infra-config:
  config:
    cdnSvc: files-rs.edgeorchestration.intel.com
    disableCoProfile: true
    disableO11yProfile: true
    embImageUrl: files-edge-orch/repository/microvisor/uos/emb_uos_x86_64_20251113.tar.gz
    enAgentManifestTag: 1.5.8
    enMetricsEnabled: "true"
    enOutboundClients: platform-observability-collector,platform-observability-health-check,platform-observability-logging,platform-observability-metrics
    enProxyFTP: http://proxy-dmz.intel.com:911
    enProxyHTTP: http://proxy-dmz.intel.com:912
    enProxyHTTPS: http://proxy-dmz.intel.com:912
    enProxyNoProxy: .caas.intel.com,certificates.intel.com,localhost,127.0.0.0/8,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,169.254.169.254,.svc,.cluster.local,.default,.internal,.orch-platform,.orch-app,.orch-cluster,.orch-infra,.orch-database,.cattle-system,.orch-secret,.onprem,.espd.infra-host.com,.pid.infra-host.com,.espdqa.infra-host.com
    enProxySocks: http://proxy-dmz.intel.com:1080
    enServiceClients: hardware-discovery-agent,cluster-agent,platform-manageability-agent,platform-update-agent,platform-telemetry-agent
    enTokenClients: node-agent,hd-agent,cluster-agent,platform-update-agent,platform-observability-agent,platform-telemetry-agent,prometheus,connect-agent,attestation-manager,platform-manageability-agent
    extraHosts: ""
    firewallCfgAllow: |-
      [{
        "sourceIp": "",
        "ports": "2379,2380,6443,9345,10250,5473",
        "ipVer": "",
        "protocol": "tcp"
      },
      {
        "sourceIp": "",
        "ports": "7946",
        "ipVer": "",
        "protocol": ""
      },
      {
        "sourceIp": "",
        "ports": "123",
        "ipVer": "",
        "protocol": "udp"
      }]
    firewallReqAllow: |-
      [{
        "sourceIp": "cluster.onprem",
        "ports": "6443,10250",
        "ipVer": "ipv4",
        "protocol": "tcp"
      }]
    nameServers: []
    netIp: dynamic
    ntpServer: ntp1.server.org,ntp2.server.org
    omStreamSvc: onboarding-stream.cluster.onprem
    omSvc: onboarding-node.cluster.onprem
    orchAttestationStatus: attest-node.cluster.onprem:443
    orchCluster: cluster-orch-node.cluster.onprem:443
    orchDeviceManager: device-manager-node.cluster.onprem:443
    orchFileServer: files-rs.edgeorchestration.intel.com:60444
    orchInfra: infra-node.cluster.onprem:443
    orchKeycloak: keycloak.cluster.onprem:443
    orchMPSHost: mps.cluster.onprem:4433
    orchMPSWHost: mps-wss.cluster.onprem:443
    orchPlatformObsLogs: logs-node.cluster.onprem:443
    orchPlatformObsMetrics: metrics-node.cluster.onprem:443
    orchRPSHost: rps.cluster.onprem:443
    orchRPSWHost: rps-wss.cluster.onprem:443
    orchRegistry: registry-rs.edgeorchestration.intel.com:9443
    orchRelease: release.cluster.onprem
    orchTelemetry: telemetry-node.cluster.onprem:443
    orchUpdate: update-node.cluster.onprem:443
    provisioningSvc: tinkerbell-haproxy.cluster.onprem
    rsType: no-auth
    skipOSProvisioning: false
    systemConfigFsInotifyMaxUserInstances: "8192"
    systemConfigKernelPanic: "10"
    systemConfigKernelPanicOnOops: "1"
    systemConfigVmOverCommitMemory: "1"
    tinkerSvc: tinkerbell-server.cluster.onprem
inventory:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
maintenance-manager:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
networking-manager:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
onboarding-manager:
  env:
    enableTinkActionTimestamp: false
    keycloakUrl: http://platform-keycloak.orch-platform.svc.cluster.local:8080
    mode: prod
    oidc:
      clients:
        bypass:
          - cdn-boots
      oidc_server_url: http://platform-keycloak.orch-platform.svc/realms/master
    passWord: user
    tinkerActionsVersion: 1.20.2
    userName: user
    vaultRole: orch-svc
    vaultUrl: http://vault.orch-platform.svc.cluster.local:8200
  managerArgs:
    enableTracing: false
    inventoryAddress: inventory.orch-infra.svc.cluster.local:50051
    traceURL: orchestrator-observability-opentelemetry-collector.orch-platform.svc:4318
  metrics:
    enabled: false
  multiTenancy:
    enforceMultiTenancy: true
  pvc:
    storageClassName: openebs-hostpath
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
  service:
    enableIO: true
  serviceAccount:
    name: orch-svc
  traefikApiGroup: traefik.io/v1alpha1
  traefikReverseProxy:
    enabled: true
    gatewayNamespace: orch-gateway
    host:
      grpc:
        name: onboarding-node.cluster.onprem
      stream:
        name: onboarding-stream.cluster.onprem
    secretName: tls-orch
    tlsOption: gateway-tls
os-resource-manager:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
pxe-server:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
resources:
  limits:
    cpu: "64"
    memory: 64Gi
  requests:
    cpu: 1m
    memory: 1Mi
telemetry-manager:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
tenant-controller:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
tinkerbell:
  pvc:
    accessModes:
      - ReadWriteOnce
    enabled: false
    storageClassName: openebs-hostpath
  stack:
    enabled: true
    resources:
      limits:
        cpu: "64"
        memory: 64Gi
      requests:
        cpu: 200m
        memory: 256Mi
  tinkerbell_hegel: null
  tinkerbell_smee:
    additionalKernelArgs:
      - http_proxy=http://proxy-dmz.intel.com:912
      - https_proxy=http://proxy-dmz.intel.com:912
      - no_proxy=.caas.intel.com,certificates.intel.com,localhost,127.0.0.0/8,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,169.254.169.254,.svc,.cluster.local,.default,.internal,.orch-platform,.orch-app,.orch-cluster,.orch-infra,.orch-database,.cattle-system,.orch-secret,.onprem,.espd.infra-host.com,.pid.infra-host.com,.espdqa.infra-host.com
      - HTTP_PROXY=http://proxy-dmz.intel.com:912
      - HTTPS_PROXY=http://proxy-dmz.intel.com:912
      - NO_PROXY=.caas.intel.com,certificates.intel.com,localhost,127.0.0.0/8,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,169.254.169.254,.svc,.cluster.local,.default,.internal,.orch-platform,.orch-app,.orch-cluster,.orch-infra,.orch-database,.cattle-system,.orch-secret,.onprem,.espd.infra-host.com,.pid.infra-host.com,.espdqa.infra-host.com
      - DEBUG=false
      - TIMEOUT=120s
      - syslog_host=127.0.0.1
    traefikReverseProxy:
      enabled: true
      nginxDnsname: tinkerbell-haproxy.cluster.onprem
  tinkerbell_tink:
    controller:
      enabled: true
    enabled: true
    server:
      enabled: true
      metrics:
        enabled: false
  traefikApiGroup: traefik.io/v1alpha1
  traefikReverseProxy:
    enabled: true
    gatewayNamespace: orch-gateway
    nginxDnsname: tinkerbell-haproxy.cluster.onprem
    tinkServerDnsname: tinkerbell-server.cluster.onprem
