api:
  image:
    pullPolicy: IfNotPresent
  multiTenancy:
    enforceMultiTenancy: "true"
  oidc:
    name: keycloak-api
    oidc_env_name: OIDC_SERVER_URL
    oidc_server_url: http://platform-keycloak.orch-platform.svc/realms/master
    oidc_tls_insecure_skip_verify_env_name: OIDC_TLS_INSECURE_SKIP_VERIFY
    oidc_tls_insecure_skip_verify_value: "true"
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
  serviceArgs:
    enableAuth: true
    inventoryAddress: inventory.orch-infra.svc.cluster.local:50051
    traceURL: orchestrator-observability-opentelemetry-collector.orch-platform.svc:4318
  traefikApiGroup: traefik.io/v1alpha1
  traefikReverseProxy:
    enabled: false
apiv2:
  apiv2IngressRoute:
    apiHostname: api.cluster.onprem
  image:
    pullPolicy: IfNotPresent
  oidc:
    name: keycloak-api
    oidc_env_name: OIDC_SERVER_URL
    oidc_server_url: http://platform-keycloak.orch-platform.svc/realms/master
    oidc_tls_insecure_skip_verify_env_name: OIDC_TLS_INSECURE_SKIP_VERIFY
    oidc_tls_insecure_skip_verify_value: "true"
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
  serviceArgsGrpc:
    enableAuth: true
    inventoryAddress: inventory.orch-infra.svc.cluster.local:50051
    traceURL: orchestrator-observability-opentelemetry-collector.orch-platform.svc:4318
  serviceArgsProxy:
    enableAuth: true
    traceURL: orchestrator-observability-opentelemetry-collector.orch-platform.svc:4318
  traefikApiGroup: traefik.io/v1alpha1
  traefikReverseProxy:
    enabled: true
    tlsOption: gateway-tls
attestationstatus-manager:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
credentials:
  curlImage:
    name: badouralix/curl-jq@sha256
    pullPolicy: IfNotPresent
    tag: 8ee002ae4452b23a3c70750c5c081e95334cfe9f7968fb4d67a90d4001c29d0b
  params:
    keycloakUrl: http://platform-keycloak.orch-platform.svc.cluster.local:8080
    vaultUrl: http://vault.orch-platform.svc.cluster.local:8200
  serviceAccount:
    name: orch-svc
dkam:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
exporter:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
global:
  registry:
    imagePullSecrets: []
    name: registry-rs.edgeorchestration.intel.com/edge-orch/
host-manager:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
import:
  api:
    enabled: true
  apiv2:
    enabled: true
  credentials:
    enabled: true
  exporter:
    enabled: true
  inventory:
    enabled: true
  tenant-config:
    enabled: false
  tenant-controller:
    enabled: true
inventory:
  image:
    pullPolicy: IfNotPresent
  inventory:
    traceURL: orchestrator-observability-opentelemetry-collector.orch-platform.svc:4318
  postgresql:
    pod:
      enabled: false
      image:
        tag: 16.10-bookworm
    secrets: inventory-local-postgresql
    ssl: false
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
  serviceAccount:
    name: orch-svc
maintenance-manager:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
networking-manager:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
onboarding-manager:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
os-resource-manager:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
pxe-server:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
resources:
  limits:
    cpu: "64"
    memory: 64Gi
  requests:
    cpu: 1m
    memory: 1Mi
telemetry-manager:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
tenant-config:
  curlImage:
    name: badouralix/curl-jq@sha256
    pullPolicy: IfNotPresent
    tag: 8ee002ae4452b23a3c70750c5c081e95334cfe9f7968fb4d67a90d4001c29d0b
tenant-controller:
  managerArgs:
    inventoryAddress: inventory.orch-infra.svc.cluster.local:50051
    skipOSProvisioning: false
    traceURL: orchestrator-observability-opentelemetry-collector.orch-platform.svc:4318
  oidc:
    oidc_server_url: http://platform-keycloak.orch-platform.svc.cluster.local/realms/master
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
  serviceAccount:
    name: orch-svc
  vault:
    role: orch-svc
    url: http://vault.orch-platform.svc.cluster.local:8200
tinkerbell:
  stack:
    resources:
      limits:
        cpu: "64"
        memory: 64Gi
      requests:
        cpu: 200m
        memory: 256Mi
