controller:
  config:
    global-config-snippet: |
      ssl-default-bind-ciphers DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384
      ssl-default-bind-ciphersuites TLS_AES_256_GCM_SHA384
      ssl-default-bind-options ssl-min-ver TLSv1.2 ssl-max-ver TLSv1.3 no-tls-tickets
  defaultTLSSecret:
    enabled: true
    secretName: tls-boots
    secretNamespace: orch-boots
  extraArgs:
    - --default-ssl-certificate=orch-boots/tls-boots
  ingressClass: haproxy
  ingressClassResource:
    default: false
    enabled: true
    name: haproxy
  resources: null
  service:
    annotations:
      metallb.universe.tf/allow-shared-ip: shared-lb
    enablePorts:
      http: false
      https: true
      prometheus: false
      stat: false
    ipFamilies:
      - IPv4
    ipFamilyPolicy: SingleStack
    type: LoadBalancer
