api:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
apiv2:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
attestationstatus-manager:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
curlImage:
  name: badouralix/curl-jq@sha256
  pullPolicy: IfNotPresent
  tag: 8ee002ae4452b23a3c70750c5c081e95334cfe9f7968fb4d67a90d4001c29d0b
dkam:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
exporter:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
host-manager:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
image:
  registry: registry-rs.edgeorchestration.intel.com/edge-orch
  repository: common/keycloak-tenant-controller
imagePullSecrets: []
inventory:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
keycloak_org_groups: |-
  {
    "<org-id>_Project-Manager-Group": [
      "<org-id>_project-read-role",
      "<org-id>_project-write-role",
      "<org-id>_project-update-role",
      "<org-id>_project-delete-role"
    ]
  }
keycloak_proj_groups: |-
  {
    "<project-id>_Edge-Node-M2M-Service-Account": [
      "rs-access-r",
      "rs-proxy-r",
      "<project-id>_cat-r",
      "<project-id>_reg-r",
      "<project-id>_en-agent-rw",
      "<org-id>_<project-id>_m"
    ],
    "<project-id>_Edge-Manager-Group": [
      "account/manage-account",
      "account/view-profile",
      "<project-id>_tc-r",
      "<project-id>_ao-rw",
      "<project-id>_cat-rw",
      "<project-id>_cl-rw",
      "<project-id>_cl-tpl-rw",
      "<project-id>_reg-a",
      "<project-id>_reg-r",
      "<project-id>_im-r",
      "<project-id>_alrt-rw",
      "<org-id>_<project-id>_m"
    ],
    "<project-id>_Edge-Onboarding-Group": [
      "rs-access-r",
      "<project-id>_en-ob"
    ],
    "<project-id>_Edge-Operator-Group": [
      "account/manage-account",
      "account/view-profile",
      "<project-id>_tc-r",
      "<project-id>_ao-rw",
      "<project-id>_cat-r",
      "<project-id>_cl-r",
      "<project-id>_cl-tpl-r",
      "<project-id>_reg-r",
      "<project-id>_im-r",
      "<project-id>_alrt-r",
      "<org-id>_<project-id>_m"
    ],
    "<project-id>_Host-Manager-Group": [
      "account/manage-account",
      "account/view-profile",
      "<project-id>_tc-r",
      "<project-id>_im-rw",
      "<project-id>_en-ob",
      "<org-id>_<project-id>_m"
    ]
  }
keycloak_realm: master
keycloak_si_groups: ""
keycloakAdmin:
  client: system-client
  passwordSecret:
    key: admin-password
    name: platform-keycloak
  url: http://platform-keycloak.orch-platform.svc:8080
  user: admin
maintenance-manager:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
networking-manager:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
onboarding-manager:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
os-resource-manager:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
pxe-server:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
resources:
  limits:
    cpu: "64"
    memory: 64Gi
  requests:
    cpu: 1m
    memory: 1Mi
telemetry-manager:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
tenant-controller:
  resources:
    limits:
      cpu: "64"
      memory: 64Gi
    requests:
      cpu: 1m
      memory: 1Mi
tinkerbell:
  stack:
    resources:
      limits:
        cpu: "64"
        memory: 64Gi
      requests:
        cpu: 200m
        memory: 256Mi
