auth:
  oidc:
    idPAddr: http://platform-keycloak.orch-platform.svc
    idPDiscoveryURL: http://platform-keycloak.orch-platform.svc/realms/master
    roleMaxTTL: 1h
  orchSvcs:
    roleMaxTTL: 1h
autoInit: true
clusterDomain: cluster.onprem
image:
  registry: registry-rs.edgeorchestration.intel.com/edge-orch
  repository: common/secrets-config
