emptyReleaseServiceToken: "true"
image:
  registry: registry-rs.edgeorchestration.intel.com/edge-orch
  repository: common/token-fs
releaseMatchHost: Host(`release.cluster.onprem`)
tlsOption: gateway-tls
traefikApiGroup: traefik.io/v1alpha1
