additionalArguments:
  - --experimental.localPlugins.jwt.moduleName=github.com/team-carepay/traefik-jwt-plugin
additionalVolumeMounts:
  - mountPath: ./plugins-local/src/github.com/team-carepay/traefik-jwt-plugin/
    name: jwt-plugin
deployment:
  podAnnotations:
    sidecar.istio.io/inject: "false"
ingressRoute:
  dashboard:
    enabled: false
logs:
  access:
    enabled: true
    format: json
  general:
    format: json
metrics:
  prometheus:
    buckets: 0.1,0.3,0.6,0.9,1.2,1.5,2.0,2.5,5.0,10.0
    service:
      enabled: true
nodeSelector: {}
ports:
  tcpamt:
    expose:
      default: true
    exposedPort: 4433
    http:
      middlewares:
        - orch-gateway-tcp-rate-limit@kubernetescrd
    port: 4433
    protocol: TCP
  web:
    expose:
      default: false
  websecure:
    exposedPort: 8443
    http:
      middlewares:
        - orch-gateway-rate-limit@kubernetescrd
        - orch-gateway-cors@kubernetescrd
    nodePort: 30443
providers:
  kubernetesCRD:
    allowCrossNamespace: true
    namespaces:
      - default
      - orch-gateway
      - orch-platform
      - orch-app
      - orch-infra
      - orch-cluster
      - orch-harbor
      - cattle-system
      - connect-gateway
      - orch-ui
      - orch-secret
      - orch-iam
resources: {}
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  seccompProfile:
    type: RuntimeDefault
service:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-lb
  type: LoadBalancer
tolerations: []
volumes:
  - mountPath: ./traefik-jwt-plugin/
    name: jwt-plugin
    type: configMap
