containersecuritycontext:
  allowprivilegeescalation: false
injector:
  resources: null
  securityContext:
    container:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
  strategy:
    type: Recreate
server:
  dataStorage:
    enabled: false
  extraArgs: -config=/vault/userconfig/vault-storage-config/storage.hcl
  extraInitContainers:
    - args:
        - echo "storage \"postgresql\" { connection_url = \"postgres://$PGUSER:$PGPASSWORD@$PGHOST:$PGPORT/$PGDATABASE\" ha_enabled=\"$HA_ENABLED\" }" > /vault/userconfig/vault-storage-config/storage.hcl
      command:
        - sh
        - -c
      env:
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              key: PGUSER
              name: vault-local-postgresql
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              key: PGPASSWORD
              name: vault-local-postgresql
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              key: PGHOST
              name: vault-local-postgresql
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              key: PGPORT
              name: vault-local-postgresql
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              key: PGDATABASE
              name: vault-local-postgresql
        - name: HA_ENABLED
          value: "false"
      image: alpine:3.22.2
      name: storage-config
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - mountPath: /vault/userconfig/vault-storage-config
          name: vault-storage-config
    - args:
        - |
          EXIST=$(psql -h $PGHOST -p $PGPORT -U $PGUSER -d $PGDATABASE -t -A -c \
            "SELECT EXISTS (SELECT FROM pg_tables WHERE tablename  = 'vault_kv_store' OR tablename = 'vault_ha_locks');"
          )
          if [[ $EXIST == "t" ]]; then
            echo "Tables already exist, skipping initialization"
            exit 0
          fi

          psql -h $PGHOST -p $PGPORT -U $PGUSER -d $PGDATABASE -c \
          "CREATE TABLE vault_kv_store (
            parent_path TEXT COLLATE \"C\" NOT NULL,
            path        TEXT COLLATE \"C\",
            key         TEXT COLLATE \"C\",
            value       BYTEA,
            CONSTRAINT pkey PRIMARY KEY (path, key)
          );
          CREATE INDEX parent_path_idx ON vault_kv_store (parent_path);
          CREATE TABLE vault_ha_locks (
            ha_key      TEXT COLLATE \"C\" NOT NULL,
            ha_identity TEXT COLLATE \"C\" NOT NULL,
            ha_value    TEXT COLLATE \"C\",
            valid_until TIMESTAMP WITH TIME ZONE NOT NULL,
            CONSTRAINT ha_key PRIMARY KEY (ha_key)
          );"
      command:
        - bash
        - -x
        - -c
      env:
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              key: PGUSER
              name: vault-local-postgresql
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              key: PGPASSWORD
              name: vault-local-postgresql
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              key: PGHOST
              name: vault-local-postgresql
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              key: PGPORT
              name: vault-local-postgresql
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              key: PGDATABASE
              name: vault-local-postgresql
      image: library/postgres:14.19-alpine3.22
      name: init-table
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
  ha:
    enabled: false
    replicas: 1
  image:
    pullPolicy: IfNotPresent
    tag: 1.21.3
  logLevel: info
  resources: null
  standalone:
    config: |
      ui = true
      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
  statefulSet:
    securityContext:
      container:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
  volumeMounts:
    - mountPath: /vault/userconfig/vault-storage-config
      name: vault-storage-config
      readOnly: true
  volumes:
    - emptyDir: {}
      name: vault-storage-config
