api:
  alertManager: https://alerting-monitor.cluster.onprem
  appDeploymentManger: https://api.cluster.onprem
  appResourceManger: https://api.cluster.onprem
  catalog: https://api.cluster.onprem
  clusterOrch: https://api.cluster.onprem
  infraManager: https://api.cluster.onprem
  metadataBroker: https://api.cluster.onprem
  mps: https://api.cluster.onprem
  rps: https://api.cluster.onprem
  tenantManager: https://api.cluster.onprem
global:
  auth:
    enabled: true
    keycloak:
      client_id: webui-client
      realm: master
      url: https://keycloak.cluster.onprem
  observability:
    url: https://observability-ui.cluster.onprem
  registry:
    imagePullSecrets: []
    name: registry-rs.edgeorchestration.intel.com/edge-orch
  session_timeout: 3600
header:
  title: Edge Infrastructure Manager
nginx:
  rewrites: []
service:
  traefik:
    enabled: false
  type: ClusterIP
traefikApiGroup: traefik.io/v1alpha1
versions:
  orchestrator: 2026.1.0-dev
