\SPDX-FileCopyrightText: 2025 Intel Corporation
\
\SPDX-License-Identifier: Apache-2.0

.TH RKE2 INSTALLER "17" "November 2023" "rke2-installer-airgap 0.1.0" "User Commands"
.SH NAME
rke2-installer \- manual page for rke2-installer-airgap 0.1.0
.SH DESCRIPTION
.IP
USAGE: rke2-installer-airgap
.SH "SEE ALSO"
.IP
Website: https://github.com/open-edge-platform/edge-manageability-framework/on-prem-installers
.SH "OTHER"
.IP
Made by Intel with ❤️
.IP
This program is distributed under Apache 2.0 license.
