# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: "UI E2E Tests"
description: "Sets up the environment with necessary tools and dependencies, then runs UI E2E tests"
inputs:
  token:
    required: true
    description: "PAT token for private repositories"
  app_orch:
    required: false
    description: "Run App Orch tests"
    default: true
  cluster_orch:
    required: false
    description: "Run Cluster Orch tests"
    default: true
  infra:
    required: false
    description: "List of tests to run for Edge Infra Manager"
    default: "cypress/e2e/infra/infra-smoke.cy.ts" # set to empty string to skip
  admin:
    required: false
    description: "Run Admin tests"
    default: true
  en_serial_number:
    required: false # NOTE this is required if the infra tests are running
    description: "Serial number of the EN"
    default: ""
  en_uuid:
    required: false # NOTE this is required if the infra tests are running
    description: "UUID of the EN"
    default: ""
runs:
  using: "composite"
  steps:
    - name: Checkout UI repo
      uses: actions/checkout@v4.2.2
      with:
        repository: open-edge-platform/orch-ui
        path: orch-ui
        ref: a145d044ff73eade7a1e14d5c925108472d9aa48
        token: ${{ inputs.token }}
    - run: git log -1
      shell: bash
      working-directory: orch-ui
    - name: Cache npm dependencies
      uses: actions/setup-node@v4.2.0
      with:
        cache: "npm"
        cache-dependency-path: orch-ui/package-lock.json
    - name: Install UI test deps
      working-directory: orch-ui
      shell: bash
      run: npm ci
    - name: Run Admin Cypress tests
      if: ${{ always() && inputs.admin == 'true' }}
      working-directory: orch-ui/tests
      shell: bash
      run: |
        npx cypress run --e2e \
          -s "cypress/e2e/admin/non-org-admin-smoke.cy.ts,cypress/e2e/admin/org-admin-smoke.cy.ts"
    - name: Run Edge Infra Manager Cypress tests
      id: infra_tests
      if: ${{ always() && inputs.infra != '' }}
      working-directory: orch-ui/tests
      shell: bash
      run: |
        npx cypress run --e2e \
          -s ${{inputs.infra}} \
          --env EN_SERIAL_NUMBER=${{ inputs.en_serial_number }}
    - name: Collect Edge Infra Manager logs
      if: ${{ always() && inputs.infra != '' }}
      working-directory: orch-ui/tests
      shell: bash
      run: |
        mkdir -p cypress/logs/edgeinfra
        kubectl logs -n orch-infra -l app.kubernetes.io/name=inventory > cypress/logs/edgeinfra/inventory.log
        kubectl logs -n orch-infra -l app.kubernetes.io/name=api > cypress/logs/edgeinfra/api.log
        kubectl logs -n orch-infra -l app.kubernetes.io/name=onboarding-manager > cypress/logs/edgeinfra/onboarding-manager.log
        kubectl logs -n orch-infra -l app.kubernetes.io/name=host-manager > cypress/logs/edgeinfra/host-manager.log
        kubectl logs -n orch-infra -l app.kubernetes.io/name=dkam > cypress/logs/edgeinfra/dkam.log
        kubectl logs -n orch-infra -l app.kubernetes.io/name=os-resource-manager > cypress/logs/edgeinfra/os-resource-manager.log

        kubectl logs -n orch-iam -l app=nexus-api-gw > cypress/logs/edgeinfra/nexus-api-gw.log
        kubectl logs -n orch-gateway -l app.kubernetes.io/name=traefik > cypress/logs/edgeinfra/traefik.log

        kubectl -n enic logs $(kubectl -n enic get pods -l app=enic --no-headers | awk '{print $1}') -c fake-uuid > cypress/logs/edgeinfra/enic-fake-uuid.log
        kubectl -n enic exec -it $(kubectl -n enic get pods -l app=enic --no-headers | awk '{print $1}') -c edge-node -- journalctl -u onboard --no-tail > cypress/logs/edgeinfra/enic-onboard.log
        kubectl -n enic exec -it $(kubectl -n enic get pods -l app=enic --no-headers | awk '{print $1}') -c edge-node -- journalctl -u agents --no-tail > cypress/logs/edgeinfra/enic-agents.log
        kubectl -n enic exec -it $(kubectl -n enic get pods -l app=enic --no-headers | awk '{print $1}') -c edge-node -- journalctl -u node-agent --no-tail > cypress/logs/edgeinfra/enic-node-agent.log
        kubectl -n enic exec -it $(kubectl -n enic get pods -l app=enic --no-headers | awk '{print $1}') -c edge-node -- journalctl -u hardware-discovery-agent --no-tail > cypress/logs/edgeinfra/enic-hardware-discovery-agent.log

        kubectl get workflow -A > cypress/logs/edgeinfra/workflow.txt
        kubectl get hardware -A > cypress/logs/edgeinfra/hardware.txt
        kubectl get template -A > cypress/logs/edgeinfra/template.txt
        kubectl get workflow -n orch-infra workflow-${{ inputs.en_uuid }}-prod -o yaml || true > cypress/logs/edgeinfra/workflow-${{ inputs.en_uuid }}-prod.log
    - name: Run Cluster Orch tests
      id: cluster_orch_tests
      if: ${{ always() && inputs.cluster_orch == 'true' }}
      working-directory: orch-ui/tests
      shell: bash
      run: |
        npx cypress run --e2e \
          -s "cypress/e2e/cluster-orch/cluster-orch-smoke.cy.ts" \
          --env EN_UUID=${{ env.EN_UUID }}
    - name: Collect ClusterOrch logs
      if: ${{ always() && inputs.cluster_orch == 'true' }}
      working-directory: orch-ui/tests
      shell: bash
      run: |
        mkdir -p cypress/logs/cluster-orch

        # CAPI components
        kubectl logs -n capi-operator-system -l app=cluster-api-operator > cypress/logs/cluster-orch/cluster-api-operator.log
        kubectl logs -n capr-system -l cluster.x-k8s.io/provider=bootstrap-rke2 > cypress/logs/cluster-orch/bootstrap-rke2.log
        kubectl logs -n capr-system -l cluster.x-k8s.io/provider=control-plane-rke2 > cypress/logs/cluster-orch/control-plane-rke2.log

        # Orch components
        kubectl logs -n orch-cluster -l app=cluster-connect-gateway-gateway > cypress/logs/cluster-orch/cluster-connect-gateway-gateway.log
        kubectl logs -n orch-cluster -l app=cluster-manager-cm > cypress/logs/cluster-orch/cluster-manager-cm.log
        kubectl logs -n orch-cluster -l app=cluster-manager-controller > cypress/logs/cluster-orch/cluster-manager-controller.log
        kubectl logs -n orch-cluster -l app=southbound-api > cypress/logs/cluster-orch/southbound-api.log

        # ENiC components
        kubectl -n enic exec -it $(kubectl -n enic get pods -l app=enic --no-headers | awk '{print $1}') -c edge-node -- journalctl -xeu cluster-agent --no-tail > cypress/logs/cluster-orch/enic-cluster-agent.log
    - name: Run AppOrch Cypress tests
      id: app_orch_tests
      if: ${{ always() && inputs.app_orch == 'true' }}
      working-directory: orch-ui/tests
      shell: bash
      run: |
        npx cypress run --e2e \
          -s "cypress/e2e/app-orch/deployment-package-smoke.cy.ts"
        # These tests are not stable yet, will be enabled in a separate PR
        # npx cypress run --e2e \
        #   -s cypress/e2e/app-orch/deployment-smoke.cy.ts
    - name: Collect AppOrch logs
      if: ${{ always() && inputs.app_orch == 'true' }}
      working-directory: orch-ui/tests
      shell: bash
      run: |
        mkdir -p cypress/logs/app-orch
        kubectl logs -n orch-app -l app=app-deployment-api > cypress/logs/app-orch/app-deployment-api.log
        kubectl logs -n orch-app -l app=app-deployment-manager > cypress/logs/app-orch/app-deployment-manager.log
        kubectl logs -n orch-app -l app=app-resource-manager > cypress/logs/app-orch/app-resource-manager.log
        kubectl logs -n orch-app -l app.kubernetes.io/name=application-catalog > cypress/logs/app-orch/application-catalog.log

    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
        name: ${{ github.event_name }}-${{ github.event.number }}-cypress-reports
        path: |
          orch-ui/tests/cypress/screenshots/**/*
          orch-ui/tests/cypress/videos/*.mp4
          orch-ui/tests/cypress/reports/*
          orch-ui/tests/cypress/logs/**/*
