# Default values for keycloak-operator chart
operator:
  namespace: keycloak-system

keycloak:
  enabled: true
  instanceName: keycloak-operator-instance
  instanceNamespace: orch-platform
  instances: 1
  
  hostname:
    strict: false
    
  http:
    httpEnabled: true
    httpPort: 8080
    
  proxy:
    headers: xforwarded
    
  db:
    vendor: postgres
    host: postgresql.orch-database.svc.cluster.local
    port: 5432
    database: orch-platform-platform-keycloak
    usernameSecret:
      name: platform-keycloak-local-postgresql
      key: PGUSER
    passwordSecret:
      name: platform-keycloak-local-postgresql
      key: PGPASSWORD
      
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
      
  additionalOptions:
    - name: KC_BOOTSTRAP_ADMIN_USERNAME
      value: admin
    - name: KC_BOOTSTRAP_ADMIN_PASSWORD
      value: admin
    - name: KC_PROXY_HEADERS
      value: xforwarded
    - name: KC_HOSTNAME_STRICT
      value: "false"
    - name: KC_HOSTNAME_STRICT_HTTPS
      value: "false"
      
  configCli:
    enabled: true
    auth:
      username: admin
      password: admin
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    configuration:
      realm-master.json: |
        {
          "realm": "master",
          "accountTheme": "keycloak",
          "displayName": "Keycloak"
        }