# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

runs:
  using: "composite"
  steps:
  - name: Get diagnostic information
    id: get-diagnostic-info
    if: always()
    shell: bash
    run: |
      mkdir -p kind-diagnostics
      kubectl get pods -o wide -A > kind-diagnostics/pods-list.txt
      kubectl describe pods -A > kind-diagnostics/pods-describe.txt
      mage logutils:collectArgoDiags > kind-diagnostics/argo-diag.txt
      kubectl get applications -o yaml -A > kind-diagnostics/argocd-applications.yaml
      kubectl get events -o yaml -A > kind-diagnostics/events.yaml
  - name: Upload diagnostic information to CI artifact store
    if: always()
    uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
    with:
      name: kind-diagnostics
      path: |
        kind-diagnostics/pods-list.txt
        kind-diagnostics/pods-describe.txt
        kind-diagnostics/argo-diag.txt
        kind-diagnostics/argocd-applications.yaml
        kind-diagnostics/events.yaml
      if-no-files-found: warn
