# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

inputs:
  k8s_diagnostics_args:
    description: "Arguments to pass to orch_k8s_diagnostics.py (e.g., '--errors-only --output-html --output-json')"
    required: false
    default: "--errors-only --output-html --output-json"

runs:
  using: "composite"
  steps:
  - name: Run K8s diagnostics utility
    id: run-k8s-diagnostics
    if: always()
    shell: bash
    run: |
      /usr/bin/python3 ./ci/orch_k8s_diagnostics.py ${{ inputs.k8s_diagnostics_args }}
      echo "K8s diagnostics completed with args: ${{ inputs.k8s_diagnostics_args }}"
  - name: Collect cluster diagnostic information
    id: collect-cluster-diagnostics
    if: always()
    shell: bash
    run: |
      mkdir -p cluster-diagnostics
      kubectl get pods -o wide -A > cluster-diagnostics/pods-list.txt
      kubectl get all -A > cluster-diagnostics/kubectl-get-all.txt
      kubectl describe pods -A > cluster-diagnostics/pods-describe.txt
      mage logutils:collectArgoDiags > cluster-diagnostics/argo-diag.txt
      kubectl get applications -o yaml -A > cluster-diagnostics/argocd-applications.yaml
      kubectl get events -o yaml -A > cluster-diagnostics/events.yaml
  - name: Collect pod logs
    if: always()
    shell: bash
    run: ./ci/collect_pod_logs.sh
  - name: Upload diagnostic artifacts
    if: always()
    uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
    with:
      name: diagnostics-${{ github.job }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.run_number }}-${{ github.run_attempt }}
      path: |
        cluster-diagnostics/
        pod_logs/
        diagnostics_full_*.md
        diagnostics_full_*.html
        summary.json
      retention-days: 15
      compression-level: 6
      if-no-files-found: warn