
tlsOption: "gateway-tls"
traefikApiGroup: "traefik.io/v1alpha1"
orchSecretName: tls-orch
keycloakJwksUrl: http://platform-keycloak.orch-platform.svc
keycloakJwksPath: /realms/master/protocol/openid-connect/certs
keycloakServicePort: 8080
fleetMatchHost: Host(`fleet.cluster.onprem`)
harborOciMatchHost: Host(`registry-oci.cluster.onprem`)
observabilityMatchHost: Host(`observability-ui.cluster.onprem`)
observabilityAdminMatchHost: Host(`observability-admin.cluster.onprem`)
vaultMatchHost: Host(`vault.cluster.onprem`)
rootMatchHost: Host(`cluster.onprem`)
keycloakMatchHost: Host(`keycloak.cluster.onprem`)
connectCSPs:
  - "https://keycloak.cluster.onprem"
  - "wss://vnc.cluster.onprem"
  - "https://app-service-proxy.cluster.onprem"
  - "https://app-orch.cluster.onprem"
  - "https://api.cluster.onprem"
  - "https://cluster-orch.cluster.onprem"
  - "https://metadata.cluster.onprem"
  - "https://alerting-monitor.cluster.onprem"
scriptSources:
  - "https://app-service-proxy.cluster.onprem"
connectCSPsAppOrch:
  - "https://keycloak.cluster.onprem"
clusterOrchNodeMatchHost: Host(`cluster-orch-node.cluster.onprem`)
logsNodeMatchHost: Host(`logs-node.cluster.onprem`)
metricsNodeMatchHost: Host(`metrics-node.cluster.onprem`)
giteaMatchHost: Host(`gitea.cluster.onprem`)
cors:
  enabled: true
  allowedOrigins:
    - https://cluster.onprem
    - https://web-ui.cluster.onprem
