
refreshInterval: "10m"
externalSecretsApiGroup: external-secrets.io/v1
withReleaseServiceToken: false
proxyTargetRegistry: registry-rs.edgeorchestration.intel.com
proxyTargetFiles: files-rs.edgeorchestration.intel.com
env:
  - name: https_proxy
    value: http://proxy-dmz.intel.com:912
  - name: http_proxy
    value: http://proxy-dmz.intel.com:912
  - name: no_proxy
    value: .caas.intel.com,certificates.intel.com,localhost,127.0.0.0/8,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,169.254.169.254,.svc,.cluster.local,.default,.internal,.orch-platform,.orch-app,.orch-cluster,.orch-infra,.orch-database,.cattle-system,.orch-secret,.onprem,.espd.infra-host.com,.pid.infra-host.com,.espdqa.infra-host.com
resources:
  limits:
    cpu: "64"
    memory: 64Gi
  requests:
    cpu: 1m
    memory: 1Mi
