
namespace: orch-database
annotations:
  cnpg.io/reload: "false"
host: "postgresql-cluster-rw.orch-database"
databases:
  - name: app-orch-catalog
    namespace: orch-app
  - name: platform-keycloak
    namespace: orch-platform
  - name: vault
    namespace: orch-platform
  - name: inventory
    namespace: orch-infra
  - name: alerting
    namespace: orch-infra
  - name: iam-tenancy
    namespace: orch-iam
  - name: mps
    namespace: orch-infra
  - name: rps
    namespace: orch-infra
