# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

# This file defines the schema and default values for the keycloak-operator Helm chart
# Values are provided directly by the platform-keycloak Application's valuesObject
# section in argocd/applications/templates/platform-keycloak.yaml
# The values.yaml here serves as documentation and defaults if no valuesObject is provided

clusterSpecific:
  # WebUI Client configuration
  webuiClientRootUrl: ""
  webuiRedirectUrls: []
  
  # DocsUI Client configuration
  docsuiClientRootUrl: ""
  docsuiRedirectUrls: []
  
  # Registry Client configuration
  registryClientRootUrl: ""
  
  # Telemetry Client configuration
  telemetryClientRootUrl: ""
  telemetryRedirectUrls: []
  
  # Cluster Management Client configuration
  clusterManagementClientRootUrl: ""
  clusterManagementRedirectUrls: []

# Keycloak Operator configuration
keycloak:
  instances: 1
  proxy:
    headers: xforwarded

# Database configuration
database:
  vendor: postgres
  host: orch-database-postgresql.orch-database.svc.cluster.local
  port: 5432
  database: keycloak
  existingSecret: orch-database-postgresql
  existingSecretHostKey: PGHOST
  existingSecretPortKey: PGPORT
  existingSecretUserKey: PGUSER
  existingSecretPasswordKey: PGPASSWORD
  existingSecretDatabaseKey: PGDATABASE

# HTTP configuration
http:
  port: 8080
  relativeUrls: true

# Environment proxy settings
envProxy:
  httpsProxy: ""
  httpProxy: ""
  noProxy: ""

# Realm configuration settings
realmConfig:
  displayName: "Keycloak"
  accountTheme: "keycloak"
  displayNameHtml: "<img src='https://raw.githubusercontent.com/open-edge-platform/orch-utils/73df5d1e99a81ae333d94b1c47dd9bef7fa03ae9/keycloak/one-edge-platform-login-title.png'></img>"
  defaultSignatureAlgorithm: "PS512"
  accessTokenLifespan: 3600
  ssoSessionIdleTimeout: 5400
  ssoSessionMaxLifespan: 43200
  passwordPolicy: "length(14) and digits(1) and specialChars(1) and upperCase(1) and lowerCase(1)"
  bruteForceProtected: true
  permanentLockout: false
  maxFailureWaitSeconds: 900
  minimumQuickLoginWaitSeconds: 60
  waitIncrementSeconds: 300
  quickLoginCheckMilliSeconds: 200
  maxDeltaTimeSeconds: 43200
  failureFactor: 5
