
global:
  auth:
    enabled: true
    keycloak:
      client_id: "webui-client"
      realm: "master"
  session_timeout: 3600

header:
  title: "Edge Infrastructure Manager"

service:
  type: ClusterIP
  traefik:
    enabled: true

traefikApiGroup: "traefik.io/v1alpha1"
