
reloader:
  watchGlobally: true
  deployment:
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
    containerSecurityContext:
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    resources:
      limits:
        cpu: "64"
        memory: 64Gi
      requests:
        cpu: 1m
        memory: 1Mi
