

externalSecretsApiGroup: external-secrets.io/v1
remoteNamespace: orch-gateway
refreshInterval: "10m"
targetSecretName: tls-ca
sourceSecretName: tls-orch
keyName:
  - source: ca.crt
    target: cacerts.pem
