# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

# The rule definition can be found
# https://github.com/updownpress/markdown-lint/tree/master/rules

---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

default: true
config:
  MD004:
    style: dash
  MD010:
    # Code blocks may have hard tabs.
    code_blocks: false
  MD013:
    line_length: 120
    code_blocks: false
    tables: false
  MD025:
    # Ignore the front matter title.  Pages still need a top level header (#).
    front_matter_title: ""
  MD029:
    style: ordered
  MD033:
    allowed_elements:
      - ref  # allow hugo relative reference links
      - br  # allow mermaid <br> to create new line
      - a  # allow anchors created by protoc-gen-doc and similar tools
      - img # allow images - needed if you need to define a size
      - span # allow span tags - needed if you need to highlight text in color

ignores:
  - "**/.terraform/**"
  - ".github/*"
  - SECURITY.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
