# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.operator.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "100"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.operator.name }}-group
  namespace: {{ .Values.operator.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "110"
spec:
  # AllNamespaces mode - empty targetNamespaces
  targetNamespaces: []
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ .Values.operator.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "120"
spec:
  channel: {{ .Values.operator.channel }}
  name: {{ .Values.operator.packageName }}
  source: {{ .Values.operator.source }}
  sourceNamespace: {{ .Values.operator.sourceNamespace }}
  installPlanApproval: {{ .Values.operator.installPlanApproval }}