name: Auto Label on Issue Assignment

on:
  workflow_dispatch:
  issues:
    types: [assigned]

permissions:
  issues: write

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Add label when issue is assigned
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['investigating']
            })
